### ISSUE TITLE
web worker example

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#10]
would be cool to have an example using web workers as an `effect`:

- [ ] write web worker example
- [ ] add docs (under `effects`)

cc/ @orodio - I figured you might like this :sparkles:

**Comment by orodio** [comment]
@yoshuawuyts did you have anything specific in mind?

**Comment by yoshuawuyts** [comment]
I was super impressed by the demo you had, where `n` actions brought the CPU to 100%, but the UI thread still rendered at 60fps

**Comment by yoshuawuyts** [comment]
Hmmm, tested out [webworkify](https://github.com/substack/webworkify) but it's not running properly :(

**Comment by yoshuawuyts** [comment]
Actually - I think this might be pushing it a bit. Closing for now, gonna revisit in the future!

**Comment by bloodyKnuckles** [comment]
I'm conflicted, I like the simplicity of choo and morphdom, but I also like the ability to delegate as much as possible to web workers. 

I've been working on a cycle.js web worker driver using Snabbdom here: https://github.com/bloodyKnuckles/cycle-web-worker 
Demo here: http://bloodyknuckles.neocities.org/cycle-web-worker/ 

And rxjs here: https://github.com/bloodyKnuckles/rx-web-worker 
And Virtual-DOM here: https://github.com/bloodyKnuckles/patchdom

**Comment by yoshuawuyts** [comment]
@bloodyKnuckles oh yeah it should be definitely possible - just haven't gotten it working yet and no idea how it'll perform. Remember that `choo` is pretty new, but this is something we want to solve in the TCBY stack so expect updates to come on this in the future! :sparkles:
