### ISSUE TITLE
3.0 Docs QA

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#124]
Hey, taking these notes on my phone at work so please excuse any terseness. Some of these are critical (ie. updating the view params), others are more suggestions that may not be necessary for the 3.0 release. I'm happy to submit them as PR(s) when I get home, but figured this thread may be easier than 50 PRs. GitHub needs a google docs comment accept/reject feature! Anyway hope this helps. 

- [x] Features: is state actually immutable?
- [x] Features: What is omakase?
- [x] Example: maybe send the string instead of an object?
- [x] Example: view args is 2.0
- [x] Example: run instructions suggest video and es2020 are required
- [x] Example: save as static is a bit unfamiliar. Maybe mention it's an alternative to browserify? Or take approach i did in handbook
- [x] Concepts par 2: actions aren't really objects anymore
- [x] Models: example code may suggest state needs to have namespace in it. Perhaps use another property name
- [x] Effects: mention examples, like Ajax, db, Dom
- [x] Effects: mention done callback
- [x] Subscriptions: example code is missing new done callback in effect
- [x] Router: update namespace/location property
- [x] Views: code example needs args updated to 3.0
- [x] Views: code example doesn't need payload namespace anymore
- [x] Api: handbook link broken
- [x] Api: subscriptions trigger on error? Do they also need to call done? If so, that's not documented above
- [ ] Api: the createSend() stuff is confusing. An example would be helpful. Could come later though.
- [x] app.model: actionData -> data
- [x] Api: send() should have (actionName, [data]) in header as its args
- [x] Api: done() should have ([err]) in header as its args
- [x] Api: done() mentions barracks
- [x] Api: app.router() should have [defaultRoute] in its header args
- [x] Api: app.start(): opts.history does this actually update state.location or a property within state.location? (ie. location.href)
- [x] Api: view = choo/html`html` is a confusing header
- [x] Api: view: yo-yo link URL links to bel
- [x] Api: view: would be great to include link to yo-yo/update-events.js for full list of events
- [x] Api: view: unload() also receives el as first param

**Comment by timwis** [comment]
Changelog

- [ ] mentions done() has second arg called "res" - haven't seen that before
- [ ] "Core dump" says most of choo was moved into wayfarer... did you mean barracks?

**Comment by yoshuawuyts** [comment]
Pretty much all merged; hope it's ok :sparkles: - closing for now then as we can release `3.0`! :grin:
