### ISSUE TITLE
Awesome choo

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/choo#132]
I think you've heard about the [Awesome lists](https://github.com/sindresorhus/awesome). Well, I guess that there are already enough resources and repos using choo so it would be _awesome_ to have some curated list of the framework

**Comment by yoshuawuyts** [comment]
@YerkoPalma go for it! :tada:

**Comment by YerkoPalma** [comment]
You mean that I should create the repo? haha that was unexpected :smile: I have no problem but I will definitly need help

**Comment by yoshuawuyts** [comment]
@YerkoPalma haha yeah, why not? - I'd be happy to link to it from the readme; there are a whole bunch of links around already on the readme.

Probably some others:
- [twitter story on choo](https://twitter.com/yoshuawuyts/status/730087077803528193)
- [a better frontend experience blog post](https://medium.com/@yoshuawuyts/a-better-frontend-experience-7b0498c85658) (how choo was developed over the years)
- [TCBY Youtube hangout](https://www.youtube.com/watch?v=a97Mw2z1SAI) - last month, courtesy of the Dat folks :sparkles:

**Comment by YerkoPalma** [comment]
@yoshuawuyts check [**here**](https://github.com/YerkoPalma/awesome-choo), some things to improve:

* Check the links, some of the resources posted seems to be under development.
* Obviusly, add more links.
* The _community_ title should include a gitter or something if there is any.
* I didn't know where to add the resources that you posted, sorry :( please send a PR where they fit best.
* It might be a good idea to add a CONTRIBUTING.md file.
* Finally, a suggestion, maybe it's time for a logo.

**Comment by yoshuawuyts** [comment]
Oooh, neat! Thanks heaps. I'll `awesome-choo` to the `See Also` :sparkles:

Haha - the logo is def 🚂:train::train::train::train:, or something like that - think it's looking great!

Perhaps the links I pasted could be best under "videos" / "articles" - the twitter thing is almost like an official resource haha; quite like the live dev blog :p

There's a contributing file under `.github/` (new thing, they added it recently) annd eehhh yeah, should probs add a gitter or something at some point - but wanna get the IRC bridge up before that hah

I'll PR some stuff in then, thanks again!
