### ISSUE TITLE
Improve Effects documentation

### ISSUE THREAD

**Issue by HoverBaum** [yoshuawuyts/choo#138]
I feel the documentation for effects is leaving out some key points:
- You can not define an effect with the same name as a reducer
- What signature can an effect have?

I figured the first one out by messing around. Thought at first I might be able to do something on the side. In my case naively saving things. A more sensible things might me analytics of some sort.

The second one I looked at [the todo example](https://github.com/shuhei/todomvc-choo/blob/master/model.js#L4) and am currently hoping that it uses the correct signature.

**Comment by yoshuawuyts** [comment]
@hoverbaum you're completely right - sorry for not replying sooner, this one accidentally fell of the radar. I'm working on better docs, as this is one of the major thing people trip over and we _want to be the very best_. Thanks again for reporting! :grin:

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
