### ISSUE TITLE
createSend is not a function in onError handler

### ISSUE THREAD

**Issue by fyrkant** [yoshuawuyts/choo#142]
### Expected behavior

Running the http example and pressing the `Naughty` button should create an error that is sent up to the onError handler, which in its turn should display the error on page. 
### Actual behavior

The onError handler fails with error `createSend is not a function`.
### Steps to reproduce behavior

Clone main repo, npm install, cd to http example, npm install, npm start and then press `Naughty` button.

**Comment by mw222rs** [comment]
Problem with barracks, seems like the second and third parameters (state and createSend) gets lost [here](https://github.com/yoshuawuyts/barracks/blob/master/index.js#L212) in wrapOnError.

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
