### ISSUE TITLE
idea: allow injecting wrappers to support different async paradigms

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#145]
I'm a huge fan of [pull-stream](https://github.com/pull-stream/pull-stream), and would love to have it be a first-class citizen in `choo`. But I know that people can be picky about their preferences for async paradigms, so I reckon the best solution would be to add some sort of wrapping hook so `choo` can be extended to accomodate all flavors of async at no extra cost.

I reckon the API could be something like:
```js
// each wrapper expects a function to be returned
app({
  wrapSubscriptions: (fn) => {},
  wrapReducers: (fn) => {},
  wrapEffects: (fn) => {}
})
```
With a little node core streams example (as that's the paradigm I'm most comfortable with):
```js
const from = require('from2')
const pump = require('pump')

const app = choo({
  wrapEffect: (fn) => {
    return (data, state, send, done) => {
      const source = from(data)
      const sink = fn(state, send)
      pump(source, sink, (err, res) => {
        if (err) return done(err)
        done(null, res)
      })
    }
  }
})
```
Lil consideration I have if the API names should be plural or singular. Also if this idea makes sense at all, hah 😛 - reckon if done well enough it could ease up some of the (unfortunately necessary) rough edges around async that were introduced in `v3`. Thanks! :sparkles:

**Comment by timwis** [comment]
Would `run-series`/`run-parallel` be another use case? Haven't used pull streams before so just trying to visualize.

**Comment by yoshuawuyts** [comment]
@timwis `run-series` / `run-parallel` operate on callbacks, so they should be fine in the current setup I reckon. Other stuff could for example be a Promise wrapper, or `async / await` (though I refuse to ever let any Promise / `a/a` examples slip in haha)

**Comment by yoshuawuyts** [comment]
This was added in `choo@3.3.0` :tada: - closing!
