### ISSUE TITLE
help with streams

### ISSUE THREAD

**Issue by mclouvem** [yoshuawuyts/choo#146]
Hi @yoshuawuyts, you are making a great job with choo and all other utilities. It's been a fun time learning reaaly good stuff here, but I'm having some hard time trying to wrap my mind around streams and app.model.
How can a return a stream from a http call storing it inside my app model? I wish I could have something similar to https://github.com/ngrx/store.

Please, accept my apologizes if I'm asking this in the wrong place.

Again congrats for this amazing job.

**Comment by yoshuawuyts** [comment]
@mclouvem hey there - so what I think you want to do is stream the response from your `effect`, and within the same effect concat it into an object that can be passed (using `send()`) to a reducer, where it is persisted in your global `state`. Streaming between effects / reducers isn't necessarily supported; although you could call `send()` multiple times and thus save data as it comes in.

Does this answer your question? Cheers!

**Comment by mclouvem** [comment]
Yes, it's totally answer my question. Thanks!

Is there some slack, gitter or irc channel to be in touch and to discuss choo?

**Comment by yoshuawuyts** [comment]
Neat! Yeah, we're on #choo on Freenode. Closing this issue now as it seems resolved 😁

**Comment by crapthings** [comment]
official slack or gitter please, this framework is so damn sexy.
