### ISSUE TITLE
Support for Typescript?

### ISSUE THREAD

**Issue by awesomektvn** [yoshuawuyts/choo#147]
Hi, Could you please add support for typescript?

**Comment by yoshuawuyts** [comment]
@awesomektvn Nope, my time is valuable an I have no interest in TS. If you want typescript support I'm happy to discuss it, but I'm not going to be the one to add it. Cheers! :sparkles:

**Comment by sotojuan** [comment]
This would just need someone who is good at TypeScript that can add type definitions `*.d.ts` files in the project root. Whether you want files like that in the project root is up to you but my point is that it'd just take someone who likes choo and TypeScript to do it :-) We have them in AVA and no one in the team uses TypeScript.

**Comment by toddself** [comment]
@sotojuan but this then becomes a maintenance issue.  Unless a contributor is willing to actively maintain the `*.d.ts` files they'll likely fall out of date quickly.

As far as I am aware, we would need to provide changes to this every time that any of the arguments or exports change in the public api (at the very least)

**Comment by sotojuan** [comment]
Good point—was just saying. Unless we have a dedicated TypeScript person I do agree it's not worth it.

**Comment by yoshuawuyts** [comment]
Alright then, I'll close this for now then until someone steps up that is willing to maintain type definitions - we can revisit the issue then :sparkles:
