### ISSUE TITLE
logging hooks for actions and state

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#15]
In development I want to hook into choo to log all actions as they happen, and having access to state so I can bind it to `window.state` - it would make debugging a lot better

**Comment by yoshuawuyts** [comment]
As per @mattmueller's suggestion, we should have the necessary hooks to support things like https://github.com/fcomb/redux-diff-logger as they've proven to dramatically improve development experience

**Comment by yoshuawuyts** [comment]
Think all that's needed is a `*` operator in `effects`. E.g.
```js
const app = choo()
app.model({
  effects: {
    '*': function (state, action) {
      window.state = state
      console.log(action.type, action)
    }
  }
})
```
For toggling can wrap in an `if (window.debug)` inside the `effect`

**Comment by yoshuawuyts** [comment]
`ember` devtools does some interesting things that we might want to allow to be done:
- status of promises (would be `actions` in `choo`)
- deprecation of framework methods (not sure that's important tho)
- rendering time per element on the page (probably done through `.onload()`, diffing with start time)
- see the values inside the data store at any given time (would be `choo` state)

**Comment by timwis** [comment]
Effects are good because we wouldn't want this to trigger a rerender

**Comment by yoshuawuyts** [comment]
With #34 in mind, I think the way to go is to create kv action hooks on start:
```js
app.start({
  hooks: {
    error: 'app:error',
    all: 'app:log'
  }
})
```
Probably `error` and `all` are the right initial hooks. `error` being what's called in callbacks for effects when they need a general error handler; makes sure that models are completely decoupled from the rest of the application, but still have a way of propagating errors. Yay, feeling good about this

**Comment by yoshuawuyts** [comment]
or maybe:
```js
app.start({
  onError: 'app:error',
  onAll: 'app:log'
})
```
Though I quite like the namespacing of `hooks`; ah well

**Comment by timwis** [comment]
Would you mind elaborating @yoshuawuyts? I don't understand why this would be preferable over a `'*'` effect. The cost of it is another concept - the `'*'` effect seemed to fit in with existing concepts.

**Comment by yoshuawuyts** [comment]
Alright - so using `*` special-cases logging hooks somewhere in the tree. When looking at the application index it won't be apparent where the logging call is done, and that can be problematic because it's definitely special.

I _really_ want namespaced models to be standalone and not require any knowledge about other parts of the application. The less leaky the abstractions, the more parallelized development can be.

In this case there's not only a need for a `logging` hook, but also for an `error` hook in lieu of #34. That way when an async action happens, and an error needs to be sent into the rest of the app there will be a standard way of doing that from within a namespaced model.

I feel that both these hooks are fairly special, and quite similar. That's why I think putting them front and center in the application is good. By looking at the index it then becomes quickly apparent which action is called to log, and which action is called to handle errors - keeping the application easy to reason about.

**Comment by timwis** [comment]
Forgot to say thanks for the background!

**Comment by yoshuawuyts** [comment]
Closing as 3.0 is imminent; wanna make sure all issues are taken care of. Releasing soooon™ :sparkles:

Will update `barracks` for `onStateChange` though :grin:
