### ISSUE TITLE
"Uncaught ReferenceError" webpack compatibility

### ISSUE THREAD

**Issue by crapthings** [yoshuawuyts/choo#157]
that's not a sheet-router issue

https://github.com/yoshuawuyts/sheet-router/issues/28

node v4.4.7 (npm v2.15.8)
webpack 1.13

    {
      "name": "webpack-choo-testfield",
      "version": "1.0.0",
      "description": "",
      "main": "./src/loader.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "dev": "webpack-dev-server"
      },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "autoprefixer": "^6.3.7",
        "babel-core": "^6.10.4",
        "babel-loader": "^6.2.4",
        "babel-plugin-transform-runtime": "^6.9.0",
        "babel-preset-es2015": "^6.9.0",
        "babel-preset-stage-0": "^6.5.0",
        "coffee-loader": "^0.7.2",
        "coffee-script": "^1.10.0",
        "css-loader": "^0.23.1",
        "exports-loader": "^0.6.3",
        "extract-text-webpack-plugin": "^1.0.1",
        "handlebars": "^4.0.5",
        "handlebars-loader": "^1.3.0",
        "html-webpack-plugin": "^2.22.0",
        "nib": "^1.1.0",
        "postcss-loader": "^0.9.1",
        "postcss-short": "^1.4.0",
        "raw-loader": "^0.5.1",
        "style-loader": "^0.13.1",
        "stylus": "^0.54.5",
        "stylus-loader": "^2.1.1",
        "webpack": "^1.13.1",
        "webpack-dev-server": "^1.14.1"
      },
      "dependencies": {
        "babel-polyfill": "^6.9.1",
        "babel-runtime": "^6.9.2",
        "choo": "^3.0.2",
        "faker": "^3.1.0",
        "lodash": "^4.13.1",
        "moment": "^2.14.1"
      }
    }

**Comment by yoshuawuyts** [comment]
Tbh I've got no idea what kind of black magic `webpack` pulls to overload `require` in Node and render applications. As a maintainer I really don't want to deal with `webpack` because of issues like this.

I'd be happy to recommend alternative tools such as [budo](https://github.com/mattdesl/budo). Perhaps someone else has interest in both `webpack` and `choo` and is willing to dig into this, but that person is not me. Sorry about that, and heaps good luck!

**Comment by drewschrauf** [comment]
FWIW, I had a issue running choo with webpack when the `devtool` was set to `eval`. I changed it to `source-map` and things started working fine.

**Comment by crapthings** [comment]
thanks @drewschrauf 

i ll try it~

**Comment by crapthings** [comment]
it works~

**Comment by crapthings** [comment]
i've tested, that is a chrome bug

https://github.com/webpack/webpack/issues/2756#issuecomment-232272889

with cheap-eval safari work
