### ISSUE TITLE
Question: Large applications and component communication

### ISSUE THREAD

**Issue by ajoslin** [yoshuawuyts/choo#16]
I haven't tried this yet, only looking at the examples. But I'm interested.  I'm wondering, what's the ideal way to handle this use-case within choo:

Somewhere deep in my app there's a button which, when clicked, opens a modal at the root level.

What's the expected way for the view containing the button to communicate to the root view? Do you recommend just `send('root:openModal', {payload: data})`? 

I'd prefer my child components not have knowledge of the root component. Do you have a suggested architecture for these kind of cases?

**Comment by yoshuawuyts** [comment]
Given that the button must trigger an action, the child component must contain _some knowledge_. What I usually do is make the button change the `url`, and based on the `url` trigger the new modal.

Managing large applications is a hard problem though, regardless of framework. The best I can hope choo can do for now is to restore sanity to the way data flows in applications.

I hope this answer was somewhat helpful!

**Comment by ajoslin** [comment]
Makes since. I agree, managing large apps and communication across that app is always a hard problem to solve correctly.

In Mercury, what I've been doing is manually bubbling an event from my deep component all the way up to the root so the root knows what happened. It's a *lot* of trouble.

I like the idea of using URLs to manage my app's popups, though. I might try that, using query parameters.

I hope to try choo very soon, too. I love the look of it. Thanks!
