### ISSUE TITLE
UMD build should build html.js

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#160]
Per #108, the [new UMD build process](https://github.com/yoshuawuyts/choo/pull/159/files) should also build `choo/html.js` so that you can construct DOM.

**Comment by marshallswain** [comment]
Related to https://github.com/maxogden/yo-yo/issues/38

**Comment by MattMcFarland** [comment]
I added a fix for this but now I'm wondering if we should remove html from choo.js as well because otherwise html is loaded twice, that being said we would end up forcing people to must use html.js though which I dont know if that is what we want.  

Personally I'd prefer separating them.

**Comment by YerkoPalma** [comment]
@MattMcFarland  What do you mean by

>html is loaded twice

**Comment by MattMcFarland** [comment]
So the build script I thought was exposing both html and choo already., otherwise the example wouldn't have ever worked?  Perhaps it wasnt working lol.  I tested this and it was working.

**Comment by MattMcFarland** [comment]
Ok I was wrong..

@YerkoPalma I actually fixed a bug :)

vanilla example only works with the changes in this PR :)

**Comment by YerkoPalma** [comment]
Yeah, I noticed when I try to make a choo example on jsfiddle. thats why I didn't understand the idea of separate things :smile: I think that the PR should be merged and the html package, that is just yo-yo, should keep the same :+1:

**Comment by MattMcFarland** [comment]
Can we close this one? :)
