### ISSUE TITLE
Build script error in MacOS El Capitan

### ISSUE THREAD

**Issue by marshallswain** [yoshuawuyts/choo#168]
### Expected behavior
The build script (`npm build:dev`) should run without errors.

### Actual behavior
The build script does not finish successfully due to the following error.
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./scripts/build: line 24: ./../node_modules/.bin/browserify: No such file or directory
```

### Steps to reproduce behavior
Clone the repo.
Run `npm install`
Run the build script using MacOS El Capitan's bash shell.  `npm run build:dev`

Are there any prerequisites I need to install?

**Comment by marshallswain** [comment]
I was able to get it to run by doing `brew install coreutils` and adding a line to the top of the build script:

```
alias readlink=greadlink
dirname=$(dirname "$(readlink -f "$0")")

browserify="$dirname/../node_modules/.bin/browserify"
uglify="$dirname/../node_modules/.bin/uglifyjs"
```

Based on this answer: http://stackoverflow.com/a/4031502/401899

**Comment by toddself** [comment]
Do you have xcode or the command line tools installed for os x?

**Comment by marshallswain** [comment]
Yeah.  I have xcode installed.

**Comment by toddself** [comment]
Just xcode or the command line tools as well? Xcode installs stuff in odd locations and doesn't provide a full suite of utilities. Trying to sort out a solution that doesn't require honewbrew

**Comment by marshallswain** [comment]
I had to [double check](http://stackoverflow.com/questions/15371925/how-to-check-if-command-line-tools-is-installed).  The xcode command line utils are installed.

**Comment by yoshuawuyts** [comment]
Typing from my phone so I'll be brief; OSX ships with super outdated core utils; readlink -f should be part of the tooling but somehow isn't; believe the solution is to update core utils and override the built ins.

Not sure if this is the way to go; but feature detection and the like are super messy in shell; idk of a better way other than telling people they should update their coreutils :/

**Comment by marshallswain** [comment]
Makes sense.  To add to the OSX oddness, the `-f` flag was mentioned in the bundled `man readlink` docs.

**Comment by yoshuawuyts** [comment]
I updated to El Capitan a couple of days ago. If you add this to your shell rc you should be good to go :sparkles::
```sh
# override built-in coreutils
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
export PATH="$(brew --prefix gnu-tar)/libexec/gnubin:$PATH"
export PATH="$(brew --prefix curl)/bin:$PATH"

# link man pages to new coreutils
export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"
export PATH="$(brew --prefix gnu-tar)/libexec/gnuman:$PATH"
export MANPATH="$(brew --prefix gnu-sed)/share/man:$MANPATH"
```

I reckon if anyone stumbled up on this they should be able to resolve it. Not a hard issue as it's mostly just build tooling but yeah

**Comment by marshallswain** [comment]
Cool.  That looks like a more elegant solution.  Thanks!
