### ISSUE TITLE
How does it compare to RiotJS?

### ISSUE THREAD

**Issue by depoulo** [yoshuawuyts/choo#169]
Hi, loving the idea, considering using choo, but unsure how it compares to RiotJS. Maybe you can share your opinion...

**Comment by marshallswain** [comment]
I've never used riot, but just from looking at it, I see a few differences.  

Riot allows custom XML-style elements (like `<todo></todo>`) and a custom curly braces solution for intermingling JavaScript.  They do require a little bit of extra work to setup.  Looks like one line of separate JS code per custom element. `riot.mount('todo')`
Choo templates are standard ES6 strings.  View functions take the place of custom elements.  There's currently no transform step to associate `<todo></todo>` with a view function like `todoView(state)`.

It looks like Riot uses traditional Observables (event emitter wrappers around your plain object literals & arrays).  Choo uses plain JS objects & arrays and would probably work better with "modern" Observables (RxJS-style), but again, I haven't used Riot, so I really don't know specifically.

Riot doesn't seem to enforce any specific architecture, but does claim the same flexibility as is allowed in Flux.  This is probably related to Riot using traditional Observables, and it's pretty typical to register callbacks on event emitters.  
Choo is based on the Elm architecture / Redux.  You can check out these articles on the [pros](http://stackoverflow.com/questions/32461229/why-use-redux-over-facebook-flux) and [cons](http://stackoverflow.com/questions/32021763/what-could-be-the-downsides-of-using-redux-instead-of-flux/32916602#32916602) of Redux vs Flux.

As a disclaimer, I'm new here.  So if I'm off base on anything, then hopefully the community will help clarify.  :)

**Comment by depoulo** [comment]
@yoshuawuyts feel free to close this and/or add an according section in the Readme.

**Comment by yoshuawuyts** [comment]
haha, so I haven't tried Riot; remember seeing stuff I didn't like - don't feel I can quite say anything sensible about it hah - but yeah cool, I'll close this issue then (':
