### ISSUE TITLE
choo.min.js Uncaught ReferenceError: assert is not defined

### ISSUE THREAD

**Issue by marshallswain** [yoshuawuyts/choo#172]
### Expected behavior
Using the minified script should work the same as the non-minified version.

### Actual behavior
Using npmcdn.com/choo@3.1.1/dist/choo.min.js causes "Uncaught ReferenceError: assert is not defined".  

npmcdn.com/choo@3.1.1/dist/choo.js does not throw the error.

### Steps to reproduce behavior
Add the script to the page, then try to initialize the demo todo app from the handbook.  (or probably any app, but that's the one I've tested) 

There are additional scripts that are needed in order to do a basic demo.  I've put yo-yo.js, xtend.js and the demo app.js I'm using in this gist: https://gist.github.com/marshallswain/09e3e223bbfde3edf5dcbc3f134498c8

**Comment by marshallswain** [comment]
Heh.  Probably related to https://github.com/yoshuawuyts/choo/issues/171

**Comment by lchski** [comment]
@marshallswain definitely looks similar to the issue I had! Though my setup is a bit different (I’m using a `package.json`-managed set of scripts, not pulling from the CDN), I put together notes on a fix that works for me in #171; I imagine that once/if it gets merged in and the CDN script updated, it should work for you as well!

**Comment by lchski** [comment]
With #173 and https://github.com/yoshuawuyts/nanoraf/pull/2 merged, once the main choo dependencies are updated, a new release pushed out, and the CDN script updated, this should all work.

**Comment by yoshuawuyts** [comment]
Published changes as `v3.1.2` :sparkles: - this should fix it - thanks for reporting!
