### ISSUE TITLE
Do you have a good example of how nested components are composed together?

### ISSUE THREAD

**Issue by jeffbski** [yoshuawuyts/choo#181]
I would like to learn how you would nest components together into a large tree to build larger apps. 

I like the example where you compose independent components together but these appear to be vertical slices, so how do you build a tree of components in choo such that all the reducers, effects, and subscriptions compose nicely. 

I think that is key for building large apps. 

Can you point to a good example or create one?

**Comment by yoshuawuyts** [comment]
There's no particular one example that shows this off well - though I do know people've started to use this and it's sounding great so far. I think the [http](https://github.com/yoshuawuyts/choo/tree/master/examples/http) example should provide a good idea of how to create namespaced models. I hope that answers your question (sorta). Cheers! :grin:

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
