### ISSUE TITLE
Model Validation

### ISSUE THREAD

**Issue by sahlhoff** [yoshuawuyts/choo#197]
Question on model validation, should this be done in the reducers or before an action is called?

Thanks!

**Comment by yoshuawuyts** [comment]
Depending on how you validate: in the reducer if it's sync, in an effect if it's async. Hope that answers your question (':

**Comment by sahlhoff** [comment]
Perfect, ty 👍

**Comment by timwis** [comment]
Out of curiosity, is there anything wrong with this happening at the component level? For instance, passing a validate function for each field on a data table component. If it doesn't pass validation it doesn't call the save callback. This is what I'm doing in dataface, just wondering if it's bad practise
