### ISSUE TITLE
feature: add 'root' option in router 

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/choo#199]
I've recently deployed a [litle project](https://github.com/YerkoPalma/tic-tac-toe) to Github pages with choo. It works fine locally, but there is some edge case when I deploy it that I want to cover. The thing is that the repo is deployed as a [project gh-page](https://help.github.com/articles/user-organization-and-project-pages/#project-pages), so the url look like this

```
https://yerkopalma.github.io/tic-tac-toe/
```

I have defined a `/game` route, and the programatic navigation works, but the url is rewrite as 

```
https://yerkopalma.github.io/game
```

That is because the navigation changes the `href` option with the `/game` route. The problem is that

1. The expected route for the game is `https://yerkopalma.github.io/tic-tac-toe/game`
2. When I type the route `https://yerkopalma.github.io/game` it gets a 404 error, the same happens with the route above.

What seems logical to me, is to have a `root`option in the router so I can make 

```javascript
const root = 'whatever'

// not actually sure how the signature should be
app.router.root = root

app.router(route => [
  route('/', mainView),
  route('/game', gameView)
])

// resulting routes 
// /tic-tac-toe/
// /tic-tac-toe/game
```

Also (and maybe more important), I guess is expected that, choo routes be relative to the path where the app is _mounted_, I mean, if I deploy my app to `/some/cool/path/` every route should be relative to that path and not to the `/` route.

I hope I make myself clear. I'm not actually sure if this issue belongs here or in the [sheet router](https://github.com/yoshuawuyts/sheet-router)

**Comment by timwis** [comment]
Have you tried changing your links to use `./`? Ie. `<a href="./game">`

I think there's also a `<meta>` tag out there to set the base URL for links.

**Comment by yoshuawuyts** [comment]
Ah yeah, this is a valid concern. I think this should indeed best be discussed in the `sheet-router` repo.

That said @timwis is right, there's a [`<base>`](https://developer.mozilla.org/en/docs/Web/HTML/Element/base) tag that seems to do what you're describing. Could you verify it works? We could then document it in `sheet-router` and in turn in `choo-handbook`. Thanks! :grin:

**Comment by YerkoPalma** [comment]
@timwis I have no anchor tags, just some buttons that run some javascript functions, and those programmatically redirect the app. @yoshuawuyts that would cover the root option, but what happens if I'm not sure where my app is going to be mounted? or if it is mounted in different routes? I guess that is why most of front end frameworks use the hash or hashbang to mount their apps, and start routing from that route, so they are independent from the rest of the routes. 
The issue here is that programmatic redirect described [here](https://github.com/yoshuawuyts/choo/issues/165#issuecomment-232846798) rewrites the whole url, even if my root app wasn't mounted on the `/` route. I guess that any solution to this issue is higly related to [this PR](https://github.com/yoshuawuyts/choo/pull/182), so I'll wait for now :+1:

**Comment by YerkoPalma** [comment]
I'm moving this issue to sheet-router repo. this is definitly not related with choo itself. Besides, I realized that my issue is not a root issue, the problem is that I can't write in the browser the url

**Comment by YerkoPalma** [comment]
open issue here: https://github.com/yoshuawuyts/sheet-router/issues/36
