### ISSUE TITLE
Announcing choo-cli

### ISSUE THREAD

**Issue by MattMcFarland** [yoshuawuyts/choo#200]
*I'm super excited to announce that a working prototype has been created*

**Motivation**

The scaffolding tool is meant to be extremely lightweight, with as *few abstractions as possible* along with a **strong emphasis** on functional programming.

The cli is used in conjunction with templates, where the templates themselves govern how the scaffolding works. This should allow high customizability along with a clear and concise pattern to follow without abstractions around manipulating the filesytem. It is designed to use **node_modules** or a **direct path** to load your templates.

```
choo init  --template <path or node_module>
```
It looks for an exports.init and exports.generate, and exports.add.  these are used to hook to the cli where it passes `argv` data to the templates directly.

You can check it out here: 
https://github.com/trainyard/choo-cli

If you want to hack together on this or get involved you are more than welcome. There's a lot left to do, come join the fun :)

**Comment by yoshuawuyts** [comment]
I quite like the idea of a CLI hey. I feel like [create-react-app](https://github.com/facebookincubator/create-react-app) is operating at the wrong abstraction level (obfuscating complexity rather than providing a sensible starting point), but providing people with a comprehensible way to get started makes sense.

I'm curious what you envision `choo-cli` should do, and how it's different from `generator-choo`; would you you mind sharing some light on this?

**Comment by MattMcFarland** [comment]
I feel the same way about create-react-app, and I feel that way about yeoman, and even plot as well.

I would like to use a CLI that is insanely easy to hack, with minimal constraints.  Yeoman got in my way because I couldnt say "yo choo" without publishing specifically something called "generator-choo" which is not currently available. 

Plop looks pretty good too, but it also tries to constrain you to the plop eco system.

the choo-cli should not get in the developers way at all, it should never be a bottleneck.  That might be a crazy notion but I really want to strive for that.  Another thing that I'm really interested in seeing through is how choo-cli executes code.

I would like it to be able to pull and execute any code that is passed into as a template.  When someone creates a choo-cli template, they do not have to use the choo-cli at all.  This is huge I think, and very liberating.  Instead, the author of a template just has to export `init`, `add`, and `generate`

I'd also like to try out maybe using something like message passing.  The code requirements for the core component (code-cli) should be filled with pure functions and unit tested heavily.  The templates though?  Those can be anything, it doesnt matter.  Instead of users having to learn some `choo-cli` abstraction they can just create `exports` that match the `commands` passed to `choo-cli`

Hope that makes sense and sorry to ramble.. Ask more questions and we can chat too if youd like  I really want to get more people involved with this, I dont like coding alone :)

**Comment by YerkoPalma** [comment]
Talking about cli ecosystem, I liked the [vue cli](https://github.com/vuejs/vue-cli), mostly because it allows to write and install custom templates. Oficial templates are good for beginers, or quick projects, but with experience, special and unique needs start to appear, and an easy way to create your own templates is a win for me. Might work to have a look :+1:

**Comment by MattMcFarland** [comment]
I updated the (readme)[https://github.com/trainyard/choo-cli/blob/master/README.md] to explain how it works in detail and explains the "why" along with the current "how"l..  Feel free to chime in especially if you disagree or see a better architecture! I love to learn, and also I want this to work for everyone, not just me! I'm also really just enjoying building it :)

**Comment by MattMcFarland** [comment]
After looking more into plop I've decided to back off of this for now, if there arent any objections I'll close this and also take down the repo.

**Comment by MattMcFarland** [comment]
choo-cli is very close to 1.0.0 release, we have unit testing, a pretty UX, and it has been tested and working with Windows 10, Ubuntu 15, and Mac Os X

**Comment by yoshuawuyts** [comment]
I think this can safely be closed; it's among the very first things we link to in the READMe. Heaps thanks for building this @MattMcFarland  @YerkoPalma  :heart:
