### ISSUE TITLE
Effect is not called if a reducer exists with the same name

### ISSUE THREAD

**Issue by efflam** [yoshuawuyts/choo#202]
It seems that the [title exemple](https://github.com/yoshuawuyts/choo/blob/master/examples/title/client.js) is not working as expected.
The `update` reducer is called but not the `update` effect.

That would allow me to update a loading boolean to display the state of a request:

```
app.model({
  state: {
    loading: false,
    data: []
  },
  effects: {
    load: (data, state, send, done) => {
      setTimeout(()=>{
        const data = ['a', 'b', 'c']
        send('loaded', data, done)
      }, 2000)
    }
  },
  reducers: {
    load: () => ({ loading: true }),
    loaded: (data) => ({ data, loading: false })
  }
})

```

**Comment by yoshuawuyts** [comment]
Oh yeah, oops you're right. We changed the behavior of this in `choo@3`, disallowing duplicate names. Maybe we should `assert` if people try and declare that? idk - anyway, PR to fix this is welcome!

**Comment by Efflam** [comment]
OK.
How do you handle a case where a effect need to call a reducer immediately, make an async operation and call another reducer when completed ?
Something like this :

````
app.model({
  state: {
    loading: false,
    data: []
  },
  effects: {
    load: (data, state, send, done) => {
      send('loading')
      setTimeout(()=>{
        const data = ['a', 'b', 'c']
        send('loaded', data, done)
      }, 2000)
    }
  },
  reducers: {
    loading: () => ({ loading: true }),
    loaded: (data) => ({ data, loading: false })
  }
})
```

**Comment by maximilianschmitt** [comment]
@yoshuawuyts If duplicates are not allowed, is there an alternative to this pattern of showing loading state when an asynchronous action is fired?

```javascript
app.model({
  effects: {
    createTodo: () => {
      api.post('/todos')
    }
  },
  reducers: {
    createTodo: () => ({ loading: true, error: false }),
    createTodosSucceeded: () => ({ loading: false, error: false }),
    createTodosFailed: () => ({ loading: true, error: false })
  }
})
```

**Comment by timwis** [comment]
Your effect Can Begin by firing a reducer to set the loading indicator, then it can make its asynchronous call and Fire another reducer when it's complete to set the loading to false.

Here's an example that's probably overkill but in lieu of typing a custom example on my phone:
https://github.com/CityOfPhiladelphia/property-choo/blob/master/src/models/property.js

**Comment by maximilianschmitt** [comment]
So maybe naming the 'initial' reducer something like `createTodoStarted` would work.

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
