### ISSUE TITLE
Programmatic navigation doesn't change URL

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#21]
I have a form that, when submitted, saves the contents to the state (via `send`) and redirects you to another page. The documentation on [router] explains how to programmatically navigate the page:

> If you want to modify the location programmatically the reducer for the location can be called using `send('app:location', { location: href })`.

Doing this doesn't change the URL, however, so if the user reloads or bookmarks the page, they won't be taken to the right place. Would you recommend adding a line such as:

`window.history.pushState(null, null, '/foo')`

Or is there a way to accomplish that with a single line?

**Comment by yoshuawuyts** [comment]
Yeah, I think this is good. It creates a slight duplication of code with https://github.com/yoshuawuyts/sheet-router/blob/master/href.js#L27 but I think that's acceptable for the sake of modularity.

Reckon something like:
```js
const newLocation = action.location.replace(/#.*/, '')
if (window && (window.location !== newLocation) {
  window.history.pushState({}, null, href)
}
```

on https://github.com/yoshuawuyts/choo/blob/master/index.js#L189 should do the trick - you reckon?

**Comment by timwis** [comment]
That sounds good to me, though I wonder if it would be worth adding a `navigate()` method to the router itself so that you can abstract the logic for how navigation works (rather than accessing `history` in choo). That would certainly make [support for hash history](https://github.com/yoshuawuyts/sheet-router/issues/16) easier.

**Comment by yoshuawuyts** [comment]
I think for the sake of modularity it's not wise to add any knowledge of `window.location` to the router itself, but let it live in a method outside of it that can instrument the router as needed.

Back when `wayfarer` was still a lil cub project, [hash-match](https://github.com/sethvincent/hash-match) was created - perhaps it'll come in useful here.

**Comment by yoshuawuyts** [comment]
We talked over this in IRC; and making a two-way binding to the history API from a reducer is maybe not the best. It might be easier to just recommend using the DOM API. We can always revisit this in the future, but I suggest we close this for now (and document it somewhere). Cheers!
