### ISSUE TITLE
subscriptions: object or array?

### ISSUE THREAD

**Issue by ungoldman** [yoshuawuyts/choo#217]
I'm noticing in the choo docs subscriptions is referred to as an **array**: 

```js
  subscriptions: [
    (send, done) => {
      setInterval(() => {
        send('app:print', { payload: 'dog?', myOtherValue: 1000 }, (err) => {
          if (err) return done(err)
        })
      }, 1000)
    }
  ]
```

> https://github.com/yoshuawuyts/choo#subscriptions

But in the barracks docs it's a plain **object** with named keys:

```js
  subscriptions: {
    emitWoofs: (send, done) => {
      // emit a woof every second
      setInterval(() =>  send('printWoofs', { woof: 'meow?' }, done), 1000)
    }
  }
```

> https://github.com/yoshuawuyts/barracks#subscriptions

I've seen it referred to both ways -- so which should it be?

Bonus question: if subscriptions is an object, do key names have any bearing on other aspects (reducers, effects, actions)?

**Comment by yoshuawuyts** [comment]
So it used to be an array, but became an object in `v3`. This was done for consistency and making sure the names showed up correctly in debug output. PRs to fix this welcome! :sparkles:

**Comment by timwis** [comment]
wow, that's weird, i'm using an array and it still works 😨

**Comment by MattMcFarland** [comment]
Yep I am using an array as well and thought that was the only way

**Comment by yoshuawuyts** [comment]
lol, javascript

**Comment by yoshuawuyts** [comment]
think this is resolved - closing!

**Comment by Haroenv** [comment]
needs to be fixed in template-basic 😄

**Comment by yoshuawuyts** [comment]
It should be an object (:
