### ISSUE TITLE
Live reloading that preserves browser state

### ISSUE THREAD

**Issue by rexmortus** [yoshuawuyts/choo#222]
### Expected behavior
Live reloading that preserves the application's state

### Actual behavior
The browser is reloaded and the application's state is lost.

### Steps to reproduce behavior
Running it with `budo --live`

Just looking for general thoughts at this point, from anyone more experienced with the framework. If indeed it's feature that's wanted but missing (and not just that I've misconfigured my project), I'd be happy to work on this.

Thanks @yoshuawuyts and team for `choo`. I'm loving it!

**Comment by rexmortus** [comment]
So I didn't RTFM, thanks for your comments in the `README` yosh.

**Comment by yoshuawuyts** [comment]
Glad you were able to figure it out! :D
