### ISSUE TITLE
AppStart hook

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/choo#232]
Is there any `startup` hook or something like that on choo? I'm asking thinking in plugin development, I know that I could just use a content loaded event or something, but I would like to write some plugin that fire an event on startup, is there any hook for that? if it isn't, can I use one of the availaible hooks for something like that?

Thanks

**Comment by yoshuawuyts** [comment]
Yeah there is none; `choo` is loaded when the dom is done loading so it's best to create a separate package for that. If you wanna do something dirty you can write a function inside a `subscription` that will be called. There's no hard guarantees when `subscriptions` are done loading though, so YMMV. Does this answer your question?

**Comment by YerkoPalma** [comment]
Yeah, that's what I though. The thing is, that plugins only define hooks, not subscriptions. Is not actually hard to write some function called on the dom load event, it's just not _the choo way_ IMO.
Thanks for the quick answer.

**Comment by yoshuawuyts** [comment]
no yeah you're right - perhaps we should add one. Curious what the use case is though

**Comment by YerkoPalma** [comment]
In my case, I'm playing with service workers, there is an initial step of registering, that has to be done on app start, is pretty similar for almost every case, so is like copy and paste always. Is so mechanical that I though is perfect for a plugin that provides offline support automagically :+1:

**Comment by yoshuawuyts** [comment]
Ahh, yeah that's a good use case. I'm cool with adding an extra hook for this hey

**Comment by YerkoPalma** [comment]
Just curious, this hook should be added on choo or barracks?

**Comment by yoshuawuyts** [comment]
I think `choo` as `barracks` things could be started at different times, making it a weird abstraction - the thing calling `barracks` will know when it's all booted up so that'd be the place
