### ISSUE TITLE
question: handling links to outside of app

### ISSUE THREAD

**Issue by tgfjt** [yoshuawuyts/choo#234]
Hi.
There're links have relative same domain path but aren't managed by router: something like other static pages.

### Expected
1. `href: true` to the pages of choo app
2. `href: false` to the pages that are outside of choo app.

I'd like to experiment with choo to our production app little by little.
Can I handle the links?

Thanks!

**Comment by yoshuawuyts** [comment]
Yup, almost! - The 4.0 release of choo should make this possible, as https://github.com/yoshuawuyts/sheet-router/pull/27 will have landed through `sheet-router`. Does this answer your question? Cheers!

**Comment by tgfjt** [comment]
It is!
What a wonderful:)

**Comment by tgfjt** [comment]
Thank you.

**Comment by krawaller** [comment]
[PR sheet-router#27](https://github.com/yoshuawuyts/sheet-router/pull/27) looks nice, and would probably solve what I [whined to you on twitter about](https://twitter.com/krawaller/status/771569808747790336)!

But, having to tag all not-to-be-handled links still seem a bit backward and awkward, and might not always be possible. The link in question might not be rendered by the app containing the router!

Here's a thought - how about allowing to customise the behaviour of non-routed links on a higher level? Perhaps choosing between a few different modes like:

* route them to a 404 component
* leave the click alone (which is what I would want for my widget)
* intercept click but do nothing (current behaviour)

Another approach would be to supply the router with a root node, and never catch clicks outside of that (likely doing the check in the [traverse function in href.js](https://github.com/jliuhtonen/sheet-router/blob/3e8c5d53e153be58e3199385d00c3625844de04a/href.js#L18-L24)).

Also I would love to be able to render a component without the router. :)

What do you guys think?

**Comment by krawaller** [comment]
Couldn't help myself, added the root node idea to sheet-router in https://github.com/yoshuawuyts/sheet-router/pull/49.
