### ISSUE TITLE
using html() outside of view

### ISSUE THREAD

**Issue by pekeler** [yoshuawuyts/choo#235]
Sorry, this might be more of a beginner question than an actual issue.

How come this works

```JavaScript
const mainView = (state, prev, send) => html`
  <div>
    ${state.toggler ? html`<div>a</div>` : html`<div>b</div>`}
    <button onclick=${(e) => send('toggle')}>toggle</button>
  </div>
`
```

http://requirebin.com/?gist=29ec2d0e1e93a35fcbfceff403d4cb70

but this does not (it seems like the button breaks after a couple of clicks)

```JavaScript
const t1 = html`<div>a</div>`
const t2 = html`<div>b</div>`

const mainView = (state, prev, send) => html`
  <div>
    ${state.toggler ? t1 : t2}
    <button onclick=${(e) => send('toggle')}>toggle</button>
  </div>
`
```

http://requirebin.com/?gist=84b72cd72aa18da298b2bf59d6220afb

**Comment by yoshuawuyts** [comment]
Yeah so what's going on here is that `morphdom` does what it does best: mutate elements. It sees two `<div>` elements, and introduces the smallest possible change by mutating the target element to be in the desired state. In the second pass, `t1` is now equal to `t2`, so when it gets rendered it's now the same and there's nothing to do. By instantiating a new tree on each render you circumvent the issue of `morphdom`'s mutations messing up what you intended to happen.

Does this answers your question? Cheers!

**Comment by pekeler** [comment]
Ha :) That totally makes sense now. Thanks!
