### ISSUE TITLE
state.params is undefined in effects

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#241]
### Expected behavior

Effects should have access to the current `state.params`. Beyond my use case, I'd expect the `state` passed to effects, reducers, and views to be the same.
### Actual behavior

The state that's provided to effects does not include the `params` property.
### Steps to reproduce behavior

Test case: http://requirebin.com/?gist=b0650339f49b3f08bd49812b938d4a66

---

Looking at the source, it looks like this may have been a design decision because `params` is only created in the context of the router and only passed to the views. So I'll wait to hear back on whether that was intentional (or if I'm doing it wrong) before digging any deeper.

**Comment by yoshuawuyts** [comment]
They should have access to it, this def feels like a bug hmmm - though haven't thought how this interacts with namespaces - what do you think?

**Comment by timwis** [comment]
`params` is a reserved namespace already, just like `location`, no?

**Comment by yoshuawuyts** [comment]
it is, though we're not enforcing it

**Comment by dmotz** [comment]
An app I'm building is currently affected by this. The specific use case involves a network request effect that needs to know a slug in the URL's path. I can of course have the effect parse the URL on its own but that seems a bit inelegant. Any thoughts?

**Comment by yoshuawuyts** [comment]
@dmotz `params.state` exists now, and we'll be adding more info in `v4` :D

**Comment by yoshuawuyts** [comment]
`state.location.params` exists now (:

**Comment by seangenabe** [comment]
Uhmm... how exactly was this solved? `state.location.params` still isn't available from effects. I searched for `params` in `index.js` and aside from a function `wrap` (which I think what the original poster saw -- this only makes the params available from views), it only appears in `createLocationModel` which should initialize `state.location.params` but only to an empty object.

```javascript
    state: mutate(createLocation(), { params: {} }),
```
