### ISSUE TITLE
How to debounce?

### ISSUE THREAD

**Issue by pekeler** [yoshuawuyts/choo#246]
Certain events can happen too fast for the event->action->reducer->newStatus->render loop. Somewhere we need to debounce. But where's the best place to do this?

Wrapping the handler or send function every time in render() loses the debouncer's state.

Wrapping the send function every time in an effect also loses the debouncer's state and adds the problem of when to call the done callback.

**Comment by pekeler** [comment]
Does this seem like a good approach?

```JavaScript
function debounceEffect (action, wait) {
  let timeout
  let lastDone
  return function (data, state, send, done) {
    const later = function () {
      timeout = null
      lastDone = null
      send(action, data, done)
    }
    if (timeout) {
      clearTimeout(timeout)
      lastDone()
    }
    timeout = setTimeout(later, wait)
    lastDone = done
  }
}
```

```JavaScript
effects: {
  debouncedStuffInput: debounceEffect('stuffInput', 100)
},
reducers: {
  stuffInput: (data, state) => ({
    stuff: cleanup(data)
  })
}
```

```JavaScript
render = function (state, prev, send) {
  return html`
    <label>
      Stuff:
      <input
        type="text"
        value=${state.stuff}
        oninput=${(event) => send('debouncedStuffInput', event.target.value)}
      />
    </label>
  `
}
```

**Comment by pekeler** [comment]
I guess it's simpler to debounce on the element's side:

```JavaScript
const html = require('choo/html')
const debounce = require('debounce')

const inputHandler = debounce(function(event, send) {
  send('stuffInput', event.target.value)
}, 100)

module.exports = function (state, prev, send) {
  return html`
    <label>
      Stuff:
      <input
        type="text"
        value=${state.stuff}
        oninput=${(event) => inputHandler(event, send)}
      />
    </label>
  `
}
```

**Comment by reminyborg** [comment]
[nanoraf](https://github.com/yoshuawuyts/nanoraf) makes shure that the rendrer only happens every 16ms, and in most cases it should be enough.  The event->action->reducer->newStatus will always happen but that is a low cost operation. I agree with your last comment deboucing on the event handler side is a nice way of doing it.

**Comment by yoshuawuyts** [comment]
yeah, `nanoraf` guards against the loop thrashing, but it's definitely valid to also throttle on the element. Stuff like keyboard input is probably best debounced for example

**Comment by pekeler** [comment]
Cool, thanks for your feedback. I didn't know about nanoraf. And one of my reducers can take longer than 16ms on slow machines.

I kind of like the way https://github.com/ryanseddon/redux-debounced abstracts debouncing to be purely declarative in the model.

If my way of debouncing isn't too far off, I guess I can close this again.

**Comment by pekeler** [comment]
I'm seeing weird behaviour when debouncing the `input` event. When typing really fast into an input element, the cursor position suddenly and unexpectedly changes on me.

Please take a look at http://requirebin.com/?gist=42919022412c22dd083564f7f493be28 which demonstrates the problem.

The problem goes away if I don't debounce, don't bind the state to the input's value, or make the debounce time excessively great.

If I were to guess what's happening: the internal value of the input element is updated in realtime as I type. The model's state is delayed due to the debouncing. So the input element gets rerendered with that delayed state. And I guess if morphdom merges a shorter value into an input element, the cursor gets placed to the default position (all the way on the right). ... but this theory doesn't explain why the problem goes away when the debounce time is super large.

Anyone have any suggestion how to deal with this problem?

**Comment by pekeler** [comment]
In React they call form-elements that have their value attribute tied to state or props "controlled inputs" or "controlled components". And it seems that the value can't be debounced for controlled inputs. (http://stackoverflow.com/a/24679479 and http://spraso.com/managing-react-controlled-component-state/).

My view in choo is like a controlled input. So I've updated the oninput event handling to fire two actions. The first one updates the state value right away. The second one does some slower calculation and is debounced.

But even with this change, I'm still seeing the problem with the cursor jump to the end of the input when typing very fast. http://requirebin.com/?gist=4e970a56edc5537f35ccbbad66e324f1

Even removing all debouncing and "processing, there's still the jumping cursor problem. http://requirebin.com/?gist=7559b0b8b2d8344c7fabb5e8d06c25e1

**Comment by yoshuawuyts** [comment]
Choo v5 is now completely sync, so keeping the form data in sync with the rendered result should be no problem. Cheers! 

---
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
