### ISSUE TITLE
Namespaced send example in Readme

### ISSUE THREAD

**Issue by jonaskello** [yoshuawuyts/choo#251]
From the readme:

> Outside the model they're called by send('todos:add') and state.todos.items. Inside the namespaced model they're called by send('todos:add') and state.items

I suspect it should be:

Outside the model they're called by send('todos:add') and state.todos.items. Inside the namespaced model they're called by **send('add')** and state.items

Or else I don't understand because it is called the same way?

**Comment by yoshuawuyts** [comment]
It _is_ called the same way. There used to be a difference (exactly as you suspected it was), but people were running into problems with namespaces being too restrictive - so we both loosened up the `send()` call namespaces and provided a way for hierarchical `send()` calls in v3.

We might restore the namespaced behavior for `send()` as I think the cleanliness makes a lot of sense; but before we do that it's probably best to lay out a good story for async / provide sufficient examples and documentation.

Does this answer your question? Cheers!

**Comment by jonaskello** [comment]
Definitely answered my question, thanks!

A quick follow up question in the same vein. Is there a way for a namespaced model to read data from state from outside it's own namespace? I have not used choo yet just looking into it, but in my current app we have a part of state that holds immutable product data that all parts of the app are allowed to read. Trying to figure out how this would be done with choo.

**Comment by jonaskello** [comment]
Just to add to the above, it's mainly in the effects I see the need to access "global" state for namespaced modules. Another way to do it if many namespaced modules need the exact same data is that they share a reducer and project the same state within their namespaces which can then be read in the effects. Not sure if this is the recommended way in choo?

**Comment by yoshuawuyts** [comment]
@jonaskello no, namespaced models cannot read data from outside; feel free to chime in on #252 as state management is definitely an issue we're trying to resolve correctly; input of any kind would be very helpful. Thanks!
