### ISSUE TITLE
Pass options to yo.update

### ISSUE THREAD

**Issue by finnp** [yoshuawuyts/choo#255]
Hey ☺️ 

I just migrated a project from `yo-yo` to `choo`. Worked perfectly and it's much better organized now \o/ 
I'm using some options for the yo update function though, and it would be nice to be able to pass it over from choo.

Not sure what's the best name for it. Maybe just a `yoyo` key in the choo options? Happy to send a PR for this.

**Comment by yoshuawuyts** [comment]
Which options are these? keen to hear what you're doing so we can determine an appropriate API :D

**Comment by finnp** [comment]
I'm using `onBeforeElUpdated` to exclude text fields, that I don't want to be overwritten while typing.

**Comment by finnp** [comment]
I actually managed to get another work around for this. Closing this for now, as it might not be worth it to add this complexity to choo.

**Comment by timwis** [comment]
Mind posting your workaround in case others run into this? Sounded interesting
