### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by azer** [yoshuawuyts/choo#259]
### Expected behavior
Entities inside HTML get displayed as they're typed, e.g

```js
html`&#1F50D;`
```

gets outputted as:

```
&#1F50D;
```

### Actual behavior
They should appear as the unicode character.

**Comment by yoshuawuyts** [comment]
See https://github.com/shama/bel/issues/42 :sparkles:

**Comment by yoshuawuyts** [comment]
Assuming this is solved. Closing!
