### ISSUE TITLE
input demo doesn't work

### ISSUE THREAD

**Issue by jatins** [yoshuawuyts/choo#261]
### Expected behavior
http://requirebin.com/?gist=229bceda0334cf30e3044d5f5c600960
Was expecting to see some rendered content here.

### Actual behavior
Nothing renders.

### Steps to reproduce behavior
Go to http://requirebin.com/?gist=229bceda0334cf30e3044d5f5c600960

**Comment by jatins** [comment]
seems to work now.

**Comment by yoshuawuyts** [comment]
yeah believe `requirebin` was down for a couple of hours, hence the failure
