### ISSUE TITLE
Server rendering 404 handling

### ISSUE THREAD

**Issue by callum** [yoshuawuyts/choo#262]
I've recently adapted the server rendering example for my project and I noticed that 404s aren't sent with a 404 status code. This is probably so trivial that it doesn't actually matter that much, but I think it might be worth looking at.

What I'm wondering is whether there's a smart way to tell the server that the route being rendered through `.toString()` is a non-match, without clunky string checking or something like that.

Interested to hear any thoughts on this.

**Comment by yoshuawuyts** [comment]
Yeah I've thought about that, and didn't really think it mattered - what we're doing on [server-render](https://github.com/yoshuawuyts/server-render) is expose a cached production mode where we already know all the paths so can render on the server if needed. Would that work for you?

**Comment by yoshuawuyts** [comment]
@callum does that answer your question?

**Comment by callum** [comment]
I'm not sure. Let me try to explain with an example:

```js
const app = choo()
app.router('/404', route => [
  route('/404', () => html`<p>404 not found</p>`),
  route('/foo', () => html`<p>foo</p>`)
])
app.toString('/bar') // technically this is a 404, but how do we know?
```

It might be nice to be able to hook in to the routes given for your app. Imagine a server implementation like this:

```js
http.createServer((req, res) => {
  if (app.match(req.url)) {
    res.statusCode = 200
  } else {
    res.statusCode = 404
  }
  res.end(app.toString(req.url, {}))
})
```

**Comment by yoshuawuyts** [comment]
Well, based on https://github.com/yoshuawuyts/choo/issues/264 we could perhaps extract the routes ahead of time, and then if a `url` doesn't match one of those routes set the statusCode to 404, and still pass it to `choo` - would that work?

**Comment by callum** [comment]
I'm sure that would be fine. I'm not advocating a new method in choo, but it might be nice if routing was more loosely coupled with choo. Liking some of your suggestions in https://github.com/yoshuawuyts/choo/issues/264.
