### ISSUE TITLE
using toString() for server rendering in node, input elements type is changed to "text"

### ISSUE THREAD

**Issue by gr4vy** [yoshuawuyts/choo#263]
When using toString() for server rendering in node, input elements type is changed to "text".

I fixed this issue by updating min-document module to version 2.19.0.
Check out https://github.com/Raynos/min-document/pull/41

**Comment by yoshuawuyts** [comment]
Seems your assessment is right. Closing in favor of https://github.com/maxogden/yo-yo/issues/33 as we should resolve it there
