### ISSUE TITLE
Reusable choo components with chooify

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/choo#266]
First of all my apologies as this is not an issue. I have read a couple of times [this discussion](https://github.com/yoshuawuyts/choo/issues/252) about choo state model, and I started writing a browserify transform for choo. [**`chooify`**](https://github.com/YerkoPalma/chooify).

I'm just starting so is pretty much a work in progress, most of the features described in the repo are not implemented yet, what is already working is a pretty basic management of .choo files. I rewrote the title example with chooify [here](https://gist.github.com/YerkoPalma/994a217bb571e1be54601f6d38337788) so you can have a look (that is actually working).

I though in a browserify transform, so the choo repo is not affected, and I want it to show it here to know your thoughts about it. Any help and/or opinion would be appreciated.

**Comment by yoshuawuyts** [comment]
@YerkoPalma haha, it's all cool! - Feel free to open discussions about things on this repo; we'll just mark it as "discussion" and talk about things.

Though personally I wouldn't use this solution, I'm definitely interested in figuring out why you wrote this: do you feel writing stateful `choo` view + model combinations is too hard? What's triggered you to write this? (and how do you think we can we improve?)

**Comment by YerkoPalma** [comment]
> do you feel writing stateful choo view + model combinations is too hard?

Writing components isn't hard, but it can be tedious. [`bel`](https://github.com/shama/bel) elements are easy and reusable, but to add a choo model you'll have to write, to exportable elements, the view and the model. That's not actually a big deal, the thing is that with a choo model you are polluting the global app state. Think, for instance, in a calendar component, with a `selectedDate` data. Handling that in the state would make a global selectedDate, if your app include many of them you'll have a lot of dates in the state. Choo solution is namespacing, but, as you said, that can be hard to handle.
So I would like to have some way to write a component that has it's own local data, without polluting the global state, but that can fire reducers and effects to handle the global state. That would make it super easy to export the calendar component, each one with a local selectedDate, and a clean global state.

> What's triggered you to write this? (and how do you think we can we improve?)

- I think a `.choo` extension is awesome.
- I though about a pull request, but the would have been too veinvasive. A transform doesn't affect any existing choo app at all.
- Is the first time I write a browserify transform, so I wanted to try it :)
- I'm thinking in use it for some custom templates later.

The help that I would like is to know about your opinions. Fisrt of all, is it clear what I'm trying to do? Do you think is related with the [actual state management discussion](https://github.com/yoshuawuyts/choo/issues/252)? Why you wouln't use it?

Also, I'm putting it here, because most of the API design isn't definitive, and may change based on any feedback.

**Comment by tunnckoCore** [comment]
Hmm. I'm agree with the @YerkoPalma and understand his idea. But don't like that syntax of the `.choo` file.
Why not just plain html? And the model can be set in `<script></script>`? Syntax highlighting would work then.

**counter.choo**

```html
<main>
  <h1>${author}</h1>
  <p>${state.count}</p>
  <button onclick=${(e) => send('increment')}></button>
</main>
<script type="choo/javascript">{
  local: {
    author: ''
  },
  effects: {
    increment: (action, state) => ({ count: state.count + 1 })
  }
}</script>
```

Looks better. Yea script type may looks strange. But it seems that GFM and my sublime theme understands that `choo/javascript` is javascript syntax. Which is cool trick.

**Comment by tunnckoCore** [comment]
@YerkoPalma What about nested components? haha. Pure example for such thing are forms. Form is one component, but it may have other components in it? ;d Don't know just some brainstorms.. I'm not react or frontend user/dev.

**Comment by Ryuno-Ki** [comment]
Concerning the type attribute of script tag: I'd suggest to change the value to be more like Mustache/Handlebars/Angular1 name them. The former part usually denotes the format. Maybe: text/choo-template? Or text/choo-view etc.

**Comment by tunnckoCore** [comment]
ryuno, agree, but we loose the highlighting and will need additional plugins. intentionally suggest that type.

**Comment by YerkoPalma** [comment]
@tunnckoCore There are two benefits with `.choo` files.

- View and component are exportable in a single file. Normally, if you have a choo component that you want to reuse, you have to require the view (bel element) and the model (js object) separatly.
- Local scope for component model. When you define a model, it adds global a state. So think about a Form component, with a validation state. The validation state is not global, it refers only to that instance of the component, so if you have another form, used by the same component view, it would have the same validation state, which is not correct. Thats the key with .choo files, you have a local property that you can use to refers to the component local data, and is different between other components, so your global state is cleaner.

Now, as you noticed there is downsides about this approach.

I agree that the syntax might be improved, thats why I'm asking for opinions :). Now I'm not sure if your proposal is better because that syntax is though for some template engine, like handlebars. Es6 template strings are not that powerful, for instance, they don't consider conditional statements, or loop statements, just expression interpolation. But still, is a great feature to have javascript on the views, so maybe is important not to lose it. I though, maybe add package name in comment, and just asume an `html`var, just as the view arguments are assumed. Let me explain with an example.

```javascript
/* choo-view granim leaflet*/ <- those two package would be required outside view function

// any js code

html`<main> <- Now use the html function (choo/html or bel) to know what to export
</main>`
```

that would help with keeping js code in the views, otherwise we would have to create some DSL or use some existing template engine, and that is not a good idea.

**Comment by YerkoPalma** [comment]
About nested component, they are pretty much supported with the actual design. Just add them in the local property.

```javascript

// form.choo
/* choo-view */
`<form>
${input.view(state, prev, send)}
</form>`

/* choo-model */
{
  local: {
    input: require('input.choo')
  }
}
```

**Comment by tunnckoCore** [comment]
I believe you can wrap with "`" [here](https://github.com/YerkoPalma/chooify/blob/master/index.js#L68) to remove this ugly requirement in the view

```html
/* choo-view */
`<form>
${input.view(state, prev, send)}
</form>`
```

soo i believe you can do

```js
function parseView (view, local) {
  // wrap in a function that require choo/html
  // check if there is any package required
  // require the package after choo/html and before the view function
  return `(function () {
      const html = require('bel'
      const local = ${JSON5.stringify(local)}
      return (function (state, prev, send) {
        return html\`${clean(view)}\`
      }).bind(local)
  })()`
}
```
notice backticks around `${clean(view)}`

> though for some template engine, like handlebars. Es6 template strings are not that powerful, for instance, they don't consider conditional statements, or loop statements, just expression interpolation.

It's not a problem. It's the same in anyway. Also ES6 Template strings are **excellent** and they can do these things.

**Comment by tunnckoCore** [comment]
I'll come back with something working, but first I need a sleep and few hours university tomorrow.

**Comment by ungoldman** [comment]
Sorry to be the naysayer but I think an opposing viewpoint should be added to this thread 😜 

I think one of the main benefits of choo is that it doesn't introduce any new file types (like JSX for example) and doesn't break JavaScript, The Language™. The biggest appeal to me for choo is that it works without any need for build/compile steps in the [electron](https://github.com/electron/electron) environment, has a very simple API, and provides a light but robust conceptual framework for dealing with state and dom (basically react/redux: the good parts).

I also don't see needing to define models and views in separate files as a drawback. In many (most?) cases a view shouldn't need its own local state, and separating concerns like views and state seems logical to me.

Introducing a new filetype seems like a step in the wrong direction to me. There are already some attempts at creating reusable choo components (like [choodown](https://github.com/trainyard/choodown)) that could be refined without needing to create another filetype and parse/compile step to go with it.

However that said I am a grumpy old man who hates transforms for dynamic languages 👴 . If it works well for you and solves a problem elegantly then go for it -- but I would strongly prefer that a `.choo` extension not become a core requirement for using choo.

**Comment by tunnckoCore** [comment]
> become a core requirement for using choo.

@ungoldman you maybe missing something here. We are not talking for requirements or adds to the core choo. Just concepts and ideas. I was just commenting the style of `chooify` and tried to represent that all "components" stuff can be done pretty easy currently. :)

**Comment by JDvorak** [comment]
Reusable components would be a lot easier if models were [_injected_](http://www.martinfowler.com/articles/injection.html) into views explicitly. It would decouple the models from the views, and shift the abstraction toward a world where views expect a particular interface, not a specific model.  With injected model, we no longer need a coordinating file like a .choo, or have to worry so much about namespaces. In the main app file, every view is explicitly paired with a model-- Bonus: this would make re-use of the same view possible with multiple disparate models, and open the door to exploring the potential in higher order models, something like model-level plugins.

**Comment by tunnckoCore** [comment]
Just want to sahre some more thoughts.. For someone who is like more class-ish components... It's not tests, just an example. I believe it looks good too.

```js
const Link = (link, anchor) => ({
  namespace: 'ahref'
  state: { link, anchor },
  view: (html) => (state, prev, send) => html`
    <a href="${state.link}">${state.anchor}</a>
  `
})

const HelloWorld = (initialState, namespace) => ({
  namespace: typeof namespace === 'string'
    ? namespace
    : '',
  state: initialState && typeof initialState === 'object'
    ? initialState
    : {},

  actions: () => ({

  }),

  reducers: () => ({

  }),

  effects: () => ({
    print: (state, data) => {
      console.log(data.payload)
    }
  }),

  subscriptions: () => ({
    callDog: (send, done) => {
      setInterval(function () {
        var data = { payload: 'dog?', myOtherValue: 1000 }
        send('app:print', data, function (err) {
          if (err) return done(err)
        })
      }, 1000)
    }
  }),

  view: (html) => (state, prev, send) => html`
    <h1>${state.app.welcome}</h1>
    ${Link(state.app.href, state.app.text)}
  `
})

const HelloComponent = HelloWorld({
  href: 'http://i.am.charlike.online',
  text: 'i.am.charlike.online',
  welcome: 'Heya, I am Charlike Mike Reagent!!'
}, 'app')

chooComponent.render(HelloComponent, '#helloApp')

```

Where `chooComponent` could be thin wrapper for `choo/mount` and calling component's methods to add actions, reducers and etc to the model with some namespace (if defined in the component), view will be passed with `html` param for more easy access without thinking for imports and requires.

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
