### ISSUE TITLE
using an arrays map method to create elements

### ISSUE THREAD

**Issue by gr4vy** [yoshuawuyts/choo#274]
I am creating div elements using the array map method. I have code like this
`
html`
  ${state.spots.map(elem => html`
    ${spot(elem, state, prev, send)}
  `
  )}
`
`
The spot function returns a div element. The page displays all the divs created as I expect. If I navigate away from this page to another page the divs will be on the page (along with the elements that belong on the page being navigated to) and they should not be there. I fixed this issue by wrapping the above code in a root element. Normally if I leave out a root element I get a message: Uncaught Error: multiple root elements must be wrapped in an enclosing tag.

I think I should get the same Uncaught Error message from the above code snippet.

**Comment by yoshuawuyts** [comment]
ah yeah this is probably because we expect a single root to exist and ignore like all other elements. Maybe we should run an assert that the returned `tree` is indeed not an array. Good one!

**Comment by yoshuawuyts** [comment]
in choo v5 `.mount()` is picky on what it accepts

---
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
