### ISSUE TITLE
Capturing all keydown events

### ISSUE THREAD

**Issue by zeke** [yoshuawuyts/choo#281]
👋 `choo` is great! I finally got around to trying it and I'm really liking it.

I'm working on an Electron app that needs to detect all keyup events. I can do something like this in the view:

```js
return html`
  <input type="text" onkeyup=${(event) => send('handleKeyup', event)}>
`
```

But that only works if the input is focused. How can I detect `keyup` events at the `document` level, which is not accessible from the view?

**Comment by yoshuawuyts** [comment]
wooh, glad you're liking it!

The way I'd approach this is to create a subscription:
```js
const app = choo()
app.model({
  namespace: 'app',
  subscriptions: {
    keys: function (send, done) {
      window.onkeyup = (ev) => { /* handle and/or more send calls */ }
    }
  }
})
const tree = app.start()
```
This will then handle all keydown events, and allows you to call other effects from there :tada: - hope this makes sense

**Comment by YerkoPalma** [comment]
There is a PR documenting exactly this

https://github.com/yoshuawuyts/choo/pull/260/files

**Comment by zeke** [comment]
Thanks!
