### ISSUE TITLE
anchor link bug: if hash is already in url, scrollintoview isn't called

### ISSUE THREAD

**Issue by sethvincent** [yoshuawuyts/choo#283]
### Expected behavior
- user clicks anchor link & jumps to position on page
- user scrolls around, clicks same anchor link, jumps to same position on page.
### Actual behavior

When the hash of the anchor link is already in the href, page position doesn't change.
### Steps to reproduce behavior

Probable place for making revision:
https://github.com/yoshuawuyts/choo/blob/4/index.js#L151

Not sure yet if there would be side effects from removing the `data.hash !== state.hash` bit of that if statement.

**Comment by yoshuawuyts** [comment]
Oh yeah, this was intentional to make it so that it's consistent with the browser behavior. Believe it's the sole reason for that check there existing haha C:

**Comment by yoshuawuyts** [comment]
do you think this should change?

**Comment by sethvincent** [comment]
I double-checked with a couple little demos just now. Before I was kinda guessing 😅.

Currently the behavior is different than default browser behavior.

### Expected behavior with plain html:
https://anchorlinks-plainhtml.static.land

Click the anchor link, scroll around, click it again, and it keeps working.

### Different behavior with choo@4.0.0-1:
https://anchorlinks-choo.static.land

Clicking the anchor link only works once.

**Comment by yoshuawuyts** [comment]
Oh that's cool - yeah I was mimicking Github's behavior I think, which apparently is buggy. Lol, guess we can do better then C:

**Comment by yoshuawuyts** [comment]
Hmm we should probs still fix this

**Comment by yoshuawuyts** [comment]
I _think_ we fixed this hmmmm

**Comment by jekrb** [comment]
@yoshuawuyts I think this was fixed here https://github.com/yoshuawuyts/choo/pull/339

**Comment by yoshuawuyts** [comment]
Ok, ok - closing
