### ISSUE TITLE
how do i style a component ?

### ISSUE THREAD

**Issue by ramstein74** [yoshuawuyts/choo#284]
How do i style a component ?

for example vuejs do it like this
https://vuejs.org/guide/single-file-components.html

**Comment by tunnckoCore** [comment]
I think because of that all Components hype and react modern things and shits, everyone forgot what actually css and html are - things can be pretty easy and enough flexible, useful and scalable. Why not use one class/id for each component? What about to do the same `style scoped` thing and use some polyfill or something like that?

j2c, don't get me wrong, sorry :)

hf,
charlike

**Comment by ramstein74** [comment]
Thank you. No ofense taken. I´m just looking for answers and ideas, not
just questioning things.



2016-10-19 22:03 GMT+01:00 Charlike Mike Reagent <notifications@github.com>:

**Comment by timwis** [comment]
I like to use sheetify https://github.com/stackcss/sheetify

**Comment by ahdinosaur** [comment]
@ramstein74 i'm currently using `sheetify` with [tachyons css](http://tachyons.io/), works great having re-usable global static styles as plain old classes, local static styles using inline `sheetify` styles, and any local dynamic styles as inline dom styles. but honestly, most approaches listed in [`MicheleBertoli/css-in-js`](https://github.com/MicheleBertoli/css-in-js) will work with choo, everyone has their own opinions. :smile:

**Comment by yoshuawuyts** [comment]
I think this question is answered now :sparkles:

**Comment by varvarasd** [comment]
Hi,

Still not clear how to style a component in choo in development.
I, for example, am trying to migrate a project to choo.js and I'm not entirely sure what's the best option to use to add the css files in the new choo.js project in dev
Is there no way of importing style.css in development in a component.js ? 
The sheetify seems extremely tedious when migrating.. :(
