### ISSUE TITLE
not an issue 

### ISSUE THREAD

**Issue by ramstein74** [yoshuawuyts/choo#285]
can you contribute to this  with choo examples ?
http://blog.krawaller.se/jscomp/index.html

regards

**Comment by fyrkant** [comment]
We (me and @krawaller) have plans on adding choo examples when it becomes possible to config choo not to catch all click event, David even made yoshuawuyts/sheet-router#49 that has already been merged. I'm not sure when it will make its way into choo though, v4 maybe? 

So, just give it a little time and choo examples will be up!

**Comment by yoshuawuyts** [comment]
@fyrkant yeah this should be part of choo v4 - you can try it out by installing `choo@next` - I'm already running it on a project and so far so good it seems :sparkles:

**Comment by krawaller** [comment]
I just added a first Choo demo to the comparison site! With a bit of fidgeting it was possible to make v4 behave as a proper widget.

[http://blog.krawaller.se/jscomp/pages/simpleclicker_choo_vanilla_info.html](http://blog.krawaller.se/jscomp/pages/simpleclicker_choo_vanilla_info.html)

I aim to get more Choo implementations in shortly (or maybe bully @fyrkant to do it)!

PS: we're in the middle of redesigning the site (or, more accurately, designing it for the first time), and the current "graphics" are all just placeholder while we get the navigation and layout down.
