### ISSUE TITLE
https://yoshuawuyts.gitbooks.io/choo/content - site is unavailable

### ISSUE THREAD

**Issue by vasia123** [yoshuawuyts/choo#286]
Output "502 Bad Gateway" error.

**Comment by tunnckoCore** [comment]
It's okey to me. It was something temporary for sure. GitBooks is big production hosting.

**Comment by timwis** [comment]
DynDNS is being attacked today

**Comment by yoshuawuyts** [comment]
we're hosting the site on gitbook; seems gitbook is down :/

**Comment by Ryuno-Ki** [comment]
No offense, but I'm still staggered, about how vulnerable the Internet became O:

A single service can take down several parts of the world … DARPAnet wasn't designed to behave like that.
But I'm getting off-topic ^^"
