### ISSUE TITLE
Embedding tweets in choo

### ISSUE THREAD

**Issue by notenoughneon** [yoshuawuyts/choo#290]
Sorry if this is not actually a bug, but I don't know how to proceed with this issue and would appreciate any help.

I made a chat app using choo, and added support for oembedding various types of links (youtube, soundcloud, etc). I add the oembed html content to a div's innerHTML, which works fine for youtube and soundcloud, but twitter is giving me trouble. Twitter oembeds include a script that loads asynchronously and modifies the dom to apply styling.

Unstyled:
![unstyled](https://cloud.githubusercontent.com/assets/6900431/19628682/43a1360a-9918-11e6-9d5f-d0ea0f4f70ab.png)

Styled:
![styled](https://cloud.githubusercontent.com/assets/6900431/19628687/5b313374-9918-11e6-84a3-e6a7d07bf88c.png)

I tried using twttr.widgets.load() and twttr.widgets.createTweet() as documented on their website: https://dev.twitter.com/web/javascript/initialization

The problem I can't get around is that every time choo updates the view, it re-renders the tweet, causing flickering and changing the scroll position. It will also interrupt embedded media players. It seems like the dom diffing is not working properly. Stuff I tried to fix this:
- caching the modified dom element and always returning it
- overloading isSameNode() to return true
- forcing the twitter widget to use iframes instead of shadow dom

I set up a demo here: https://nekocafe-tgodwqhzlf.now.sh/
And the code is here: https://github.com/notenoughneon/nekocafe/commit/20b4bab2fe5c52b1800d626044479c4ae7686289

**Comment by timwis** [comment]
Hi @notenoughneon - we've seen this issue before with things like leaflet and d3 and other libraries that alter the DOM themselves. Try [cache-element](https://github.com/yoshuawuyts/cache-element) out for that -- it's fresh off the grill, so do let us know how it works out!

**Comment by notenoughneon** [comment]
Thanks for the suggestion! I will let you know how it goes.

**Comment by notenoughneon** [comment]
I tried wrapping the element with `cache`, but something is not working. The compare function is always receiving `0` as the `prev` value, so only the first tweet gets rendered.

https://github.com/notenoughneon/nekocafe/commit/ad73cfef2c528281e5e35cf327bb42e706136060

**Comment by yoshuawuyts** [comment]
oh yeah, I think what's going on is that you're not passing the `prev` value into the element. Each view is passed `(state, prev, send)` as arguments. This was done so that `cache-element` doesn't accidentally hold references to old data and cause memory leaks - all needs to be passed in explicitely

**Comment by yoshuawuyts** [comment]
__edit:__ hope that makes sense :sparkles:

**Comment by notenoughneon** [comment]
I'm not sure where to get `prev`. I thought that was the job of cache-element?

What I am trying to do:

```javascript
const embedTweet = (tweet) => {
    const div = html`<div>${tweet}</div>`
    twttr.widgets.load(div)    // *** slow and asynchronous ***
    return div
}

const renderWidget = someCacheFunction(embedTweet)

// the following calls to renderWidget:
renderWidget('tweet a') // creates new element
renderWidget('tweet b') // creates new element
renderWidget('tweet a') // returns cached 'a'
renderWidget('tweet b') // creates cached 'b'
renderWidget('tweet c') // creates new element
```

**Comment by yoshuawuyts** [comment]
Oh yeah so `prev` is returned by the view: the signature in choo 3.x is
`(state, prev, send)`

**Comment by notenoughneon** [comment]
I updated to choo 4, will this still work?

**Comment by yoshuawuyts** [comment]
yeah it should!

**Comment by notenoughneon** [comment]
I tried passing the `prev` values down from the root view, but it is still only rendering the first tweet.

https://github.com/notenoughneon/nekocafe/commit/808ad0648b1d8791bd8e3507a9474df7f5f77f81

**Comment by yoshuawuyts** [comment]
ah yeah I think I know what's up: `cachedEmbed` is a stateful object which
is being reused multiple times; if you wanna cache multiple elements you
should probably create multiple instances of the element in a constructor.
I think your use case makes a lot of sense, and we should probably cater
better for this. Sorry the docs on this are a bit rough 😔

**Comment by notenoughneon** [comment]
After playing around with it some more, I think I found a solution. I tried this earlier but `isSameNode` only seems to work in choo 4.

```javascript
const cache = {}

function renderOnce(render) {
    return arg => {
        if (cache[arg]) {
            const proxy = html`<div></div>`
            proxy.isSameNode = () => true
            return proxy
        }
        cache[arg] = true
        return render(arg)
    }
}

const embedRow = renderOnce((snippet) => {
    const embed = html`<div></div>`;
    embed.innerHTML = snippet;
    twttr.widgets.load(embed);
    console.log('rendering ' + snippet);
    return html`
        <div class="row">
            <div class="col-xs-12 col-md-8">
                ${embed}
            </div>
        </div>
    `;
});
```

**Comment by leeoniya** [comment]
no disrespect to `choo` or authors, but seems like a lot of contortions to get this done :/

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/demos/embed-twitter.html

**Comment by yoshuawuyts** [comment]
Yay, glad you got it to work! - from talk on IRC folks are only now
starting to use caching - the whole thing is still a bit rough; real glad
you managed to get it to work - hopefully we can soften up the docs a
little as we progress (:

**Comment by notenoughneon** [comment]
I found a couple problems with my last solution.

1. Multiple instances of the same tweet can't coexist, only one will display
2. Hiding and reshowing a tweet doesn't work

Here is my next attempt, which fixes those problems at the expense of re-invoking createTweet() on every refresh.

```javascript
const embedRow = (embed) => {
    const inner = html`<div></div>`;
    switch (embed.type) {
        case 'html':
            inner.innerHTML = embed.html;
            break;
        case 'tweet':
            twttr.widgets.createTweet(embed.id, inner);
            break;
    }
    const elt = html`
        <div class="row">
            <div class="col-xs-12 col-md-8">
                ${inner}
            </div>
        </div>
    `;
    elt.isSameNode = () => true;
    return elt;
};
```

**Comment by yoshuawuyts** [comment]
https://www.npmjs.com/package/nanocomponent exists now for this purpose - thanks!
