### ISSUE TITLE
Should the `state` object be modified directly?

### ISSUE THREAD

**Issue by zeke** [yoshuawuyts/choo#304]
I remember watching some Dan Abramov video about redux or something, and there was a bit about not mutating the state, but always returning a copy of it.

So I'm doing this in my app:

``` js
return Object.assign(state, {selectedIndex: --state.selectedIndex})
```

But should I just be modifying the state directly? Does it matter?

``` js
state.selectedIndex--
return state
```

**Comment by Ryuno-Ki** [comment]
Sine objects are passed by refernce it matters. If you touch the state object you'll have side effects. Which is against the functional programming/Redux philosophy.

**Comment by Ryuno-Ki** [comment]
s/Sine/Since/

**Comment by yoshuawuyts** [comment]
@zeke so under the hood we take the changes and run `xtend()` on it to turn it into a new state. I found the `Object.assign()` thing to be very boilerplaty and so we just do that under the hood. See this code in `barracks`: https://github.com/yoshuawuyts/barracks/blob/master/index.js#L225-L230

Under the hood we're also calling `Object.freeze()` if you're mutating things but think we might've messed it up somewhere so it isn't always called - this should help guard against mutation in most cases (e.g. it even throws in `strict mode` I believe? haha not sure). Tl;Dr: we're aware and accounting for this; we got you :grin:

I do think there's a way to converge mutation with reduced side effects and get great performance, but that's an experiment for another day (choo {5,6,7}, perhaps?)

Hope this answers your question :sparkles:

**Comment by zeke** [comment]
Sorry @yoshuawuyts but I don't fully understand your explanation.

> under the hood we take the changes and run xtend() on it to turn it into a new state

Does this mean the `state` argument I receive in the reducer function is actually a copy of the "real" state object? In other words, what is the first argument to `xtend` "under the hood"?

> Under the hood we're also calling Object.freeze()

What exactly is being frozen? It must not be the `state` argument, as it appears that I can make changes to that directly without anything breaking. From the demo:

```js
// original
increment: (data, state) => ({count: state.count + 1})
```

Can be changed to this and everything works:

```js
// mucking with the state object
increment: (data, state) => {
  state.count+=3 // modify the state
  state.foo='yay' // even add some new properties
  return state
}
```

I also tried adding `use strict` for grins and didn't see any exceptions.

> there's a way to converge mutation with reduced side effects and get great performance

What does this mean?

I'm basically asking for clarification on everything you just said! 🙈 

Once I see the light, I will try to make it worth your while by opening a PR with some helpful documentation on this topic.

**Comment by timwis** [comment]
Hm, I recall this coming up before. From the code, it looks like reducers are _not_ passed a _copy_ of the state, but the state object itself ([source](https://github.com/yoshuawuyts/barracks/blob/master/index.js#L225-L230)). I see a couple references to `Object.freeze`, but it doesn't appear to be freezing the `_state` that's passed to the reducers. Unless I'm reading it wrong?

**Comment by jbucaran** [comment]
> But should I just be modifying the state directly? Does it matter?

I think Ryuno-Ki already answered this and you already knew this and were asking from a philosophical POV? 

In any case, you shouldn't modify the state directly, instead, return a new state from each reducer.

**Comment by zeke** [comment]
> you shouldn't modify the state directly, instead, return a new state from each reducer.

Okay, that's what I'm doing until I hear some more concrete indication that it's safe to directly modify the state objects choo is giving me.

**Comment by timwis** [comment]
Note that reducers don't need to return a _whole_ new state object; they can return just a _part_ of it. Whatever the reducer returns will be applied to the state via `xtend()`, which I think may be what yosh was getting at above.

So under the hood choo is doing something like this (pseudocode):

stateUpdates = reducer(state, data)
newState = xtend(state, stateUpdates)
