### ISSUE TITLE
Effects vs reducers

### ISSUE THREAD

**Issue by dfcreative** [yoshuawuyts/choo#308]
Hi!

Sometimes I want to run one reducer from another reducer, to avoid code duplication - the first one is just a more complicated version of another, with additional logic.

In effects we have `data, state, send, done` arguments, I wonder why we don’t have `send` argument in reducers? That leads to more generic question - what is the fundamental difference between reducers and effects, why some complicated _reducers_ have no choice but become "sync" _effects_, why not just leave _effects_, which possibly return state (or `done` callback if expected), i.e. like _reducers_ now but with two more arguments? The only difference I can think of is sync/async style. From UX POV that kind of forces me to decide every time - should I put next part of the logic into reducer or effect, and it punishes with refactoring for wrong decisions.
Another concern - why I am forced to always pass callback to `send` function, if I just want to call reducer, which cannot be async? Why not allow it be skipped?

Skipping these rhetorical questions, what is the right practice to call reducer from other reducer?

**Comment by jbucaran** [comment]
@dfcreative

**Comment by dfcreative** [comment]
>  you can refactor your duplicated code into functions
That is what I eventually did [here](https://github.com/amazemontreal/rage-game-client), the real model is decoupled with choo model, which turned out to be messy for handling logic.
I found out that the only reducer having the most meaning is [`update`](https://github.com/amazemontreal/rage-game-client/blob/master/src/app.js#L230), which is basically `extend` of model, and the rest is left up to effects.
