### ISSUE TITLE
Passing router variables to models 

### ISSUE THREAD

**Issue by rollymaduk** [yoshuawuyts/choo#310]
Hi is it possible to pass router params as variables to a model?

**Comment by timwis** [comment]
Hi @rollymaduk. I assume you're trying to call an effect or a reducer on your model, and you want route params available to them. You can this by passing the route params into your `send()` call, ie.

```javascript
app.router((route) => [
  route('/:user', UserView)
])

function UserView (state, prev, send) {
  if (state.params.user !== prev.params.user) {
    send('fetchUser', state.params.user)
  }
}
```
Hope this helps

**Comment by rollymaduk** [comment]
@timwis thanks that's what I was looking for
