### ISSUE TITLE
Can I use jsdom to test my choo app?

### ISSUE THREAD

**Issue by rollymaduk** [yoshuawuyts/choo#311]
Curious.. can testing be done with jsdom  on a choo app especially with testing dom changes

**Comment by yoshuawuyts** [comment]
jsdom is a pretty limited subset of what a normal dom looks like; so
probably not for everything - though you could definitely try it out.
Personally I wouldn't really go there, as the DOM is usually only needed
for side effects / rendering - and with .toString() and model testing, most
test cases should be covered for anyway :D

**Comment by rollymaduk** [comment]
thanks... I decided to go with jsdom because I keep getting errors for choo components with the onload event attached to them.. something to do with restrictions with code having strict mode

**Comment by timwis** [comment]
I've used jsdom to test choo apps - [here's an example](https://github.com/timwis/enviar/blob/master/test/client/conversations.js).
