### ISSUE TITLE
Dots in URLs are not routed at all

### ISSUE THREAD

**Issue by mantoni** [yoshuawuyts/choo#330]
When I have a route like `/:foo/:bar`, I expect it to be matched by `/foo/1.2.3`. However, the default 404 page is shown. The same happens for `/foo/a.b` - anything with a dot really, while `/foo/123` and `/foo/ab` work as expected.

Note that my custom 404 page is shown correctly when specifying a path that does not match, but when a dot is present in the URL, it's not even rendering my custom 404.

Using choo 3.3.0 running on budo 9.2.2.

**Comment by yoshuawuyts** [comment]
Weird, routes are split here:
https://github.com/yoshuawuyts/wayfarer/blob/master/trie.js#L20 and iirc
we're not doing much else - maybe it's one of the sanitization packages
that's messing things up here? :/

**Comment by mantoni** [comment]
Ok, traced it down to [connect-pushstate](https://github.com/brentertz/connect-pushstate/blob/master/index.js#L15). It thinks I'm accessing a static file.
