### ISSUE TITLE
option to ignore subtree render

### ISSUE THREAD

**Issue by xz64** [yoshuawuyts/choo#338]
Hi,

Thanks for creating this framework. I am trying to see how feasible it is to integrate a jquery library such as selectize into this framework. It seemed to work ok until the DOM gets morphed. At that point all the selectize initialization is lost. It would be nice if we could have a way to skip a subtree when diffing the dom. It looks like morphdom (and yo-yo with some additional configuration) already support this by passing a [onBeforeElChildrenUpdated](https://github.com/patrick-steele-idem/morphdom#api) function.  I'm open to other ideas on how to approach this issue.

### Expected behavior
The select element should not get un-selectized after checking the checkbox.

### Actual behavior
Select element get un-selectized after checking the box

### Steps to reproduce behavior
See on codepen: http://codepen.io/xz64/pen/dOvgEg

**Comment by yoshuawuyts** [comment]
Try giving cache-element/widget a shot
https://github.com/yoshuawuyts/cache-element ✨

**Comment by aknuds1** [comment]
Interesting, I was just about to ask about this sort of thing, in conjunction with the D3.js library, which also manages its own subtree.

**Comment by xz64** [comment]
Thanks @yoshuawuyts , this seemed to work. I just wrapped my selectize component with the cache-element/widget function. 

The [choo-leaflet-demo](https://github.com/timwis/choo-leaflet-demo) repo was helpful in showing how to use cache-element.

**Comment by yoshuawuyts** [comment]
Yay glad!

**Comment by siuying** [comment]
I had same issue but new cache-element do not have widget... i have read the few commits and nanocomponents but its not clear how I can use the new api to wrap third party widget?
