### ISSUE TITLE
Event handlers don't get updated when replacing a visually identical element

### ISSUE THREAD

**Issue by aknuds1** [yoshuawuyts/choo#349]
I haven't created a test case for this yet, but I'm pretty sure my theory as to what's happening holds water. What I'm seeing is that when I have a table with identically looking buttons on every row, and a row gets deleted, the `onclick` handler for the deleted row remains active. I've come to this conclusion because every button's `onclick` handler is associated with an ID. When I remove a row and click the button on the row that replaces it, the `onclick` handler has the ID associated with the deleted row.

**Comment by yoshuawuyts** [comment]
I think it's the [copier method in yo-yo](https://github.com/maxogden/yo-yo/blob/master/index.js#L18-L34) not accounting for reordering of sibling nodes that's causing the issue

**Comment by aknuds1** [comment]
Thanks Yosh, will try to come up with a PR ❤️

**Comment by yoshuawuyts** [comment]
:D

**Comment by aknuds1** [comment]
As discussed on IRC, I found out that this is due to hyperscript registering event handlers via addEventListener, which doesn't mesh with yo-yo, for which you need to register event handlers via element attributes, e.g. `onclick`.

**Comment by yoshuawuyts** [comment]
I think we can close this now right? - found the error. Maybe we should add
a comment in the readme?

**Comment by aknuds1** [comment]
@yoshuawuyts Yeah, would be cool to document. I already closed it though.
