### ISSUE TITLE
update view API to be (state, prev, send)

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#35]
Since `v2.1.4` (oops, semver) we're now also passing the `oldState` down to views. The `view` api now looks like:
```js
const view = (params, state, send, oldState) => choo.view`
  <main>${params.foo} and ${state.bar}</main>
`
```
Instead I reckon it might be nicer to have:
```js
const view = (state, oldState, send) => choo.view`
  <main>${state.params.foo} and ${state.bar}</main>
`
```
This would definitely be a breaking change, but actually not that hard to fix (e.g. we can provide a regex heyyyy). What do people think?

**Comment by timwis** [comment]
:+1: to reordering the params. Would it make sense to put `params` inside the `app` namespace like `location`?

**Comment by ahdinosaur** [comment]
> Since `v2.1.4` (oops, semver) we're now also passing the `oldState` down to views.

[context](https://github.com/yoshuawuyts/choo/pull/27#issuecomment-222549654) for anyone like me who wasn't aware.

@yoshuawuyts to be honest i'm not quite sold on `oldState` being necessary in views, but happy to follow along with how `choo` develops. :smile:

**Comment by ahdinosaur** [comment]
or i'm being silly, a similar project [`vdux` also passes in previous state](https://github.com/vdux/vdux#components), as do many other projects.

**Comment by contra** [comment]
```js
const view = ({ params, state, oldState}, send) => choo.view`
  <main>${params.foo} and ${state.bar}</main>
`
```

🙏

**Comment by kristoferjoseph** [comment]
```js
const view = (state, send) => choo.view`
  <main>${state.params.foo} and ${state.bar}</main>
`
```

**Comment by yoshuawuyts** [comment]
@kristoferjoseph but where would the `oldState` go? Right now I'm leaning towards:
```js
const html = require('choo/html')
const view = (state, prev, send) => html`
  <main>${state.params.foo} and ${state.bar}</main>
`
```
We could maybe get super smart and do a `Function.prototype.length` check so that it's passed oldState, but only if it cares about it:
```js
const mainView = (state, send) => html`
  <main>${state.params.foo} and ${state.bar}</main>
`
const diffView = (state, prev, send) => html`
  <div>${prev.foo} become ${state.foo}</div>
`
```

This would have the downside that omitting `send()` would make it questionable; but I reckon that's a bit of an edge case:
```js
// prev.foo is undefined
const diffView = (state, prev) => html`
  <div>${prev.foo} become ${state.foo}</div>
`
```

@contra while in ES6 that API looks quite good, it's not that great when not on board of the babel train. I personally only use [a tiny subset](https://github.com/yoshuawuyts/es2020) of ES5 / ES6 and would rather not rely on object destructuring for this particular API

**Comment by kristoferjoseph** [comment]
@yoshuawuyts OK I can get behind passing `prev` as well. Was originally adverse to the idea of even needing `prev`, but it seems useful for more advanced optimizations like determining if you need to re-render subtrees etc. 
<rant>
I am trying to only write valid JavaScript, which is actually saying I don't want to be forced into writing babelscript anymore. If it doesn't work in any current JavaScript runtime it isn't JavaScript. right?
</rant>

**Comment by yoshuawuyts** [comment]
@kristoferjoseph haha, yeah that's the idea - but you reckon we should do the `Function.length` detection? Mainly curious what people think about that / would it be confusing? I'm not entirely convinced myself yet

**Comment by timwis** [comment]
@yoshuawuyts Regarding the `Function.length` checking, I'd worry that it's too mysterious/magical, and newcomers would think something's wrong. An alternative would be to put `send` as the _first_ parameter - then the consumer could choose to leave off `prev` if they want to and it won't break anything.

**Comment by yoshuawuyts** [comment]
@timwis yeah, you're totally right - mentally I've been geared to have data go first and any type of callback last, so we should probs just do `(state, prev, send)` :sparkles:

**Comment by kristoferjoseph** [comment]
I am not a fan of using the magical `Function.length`
Totally a valid use case for this, but three function arguments is chill.

**Comment by contra** [comment]
Just to be clear, with this new API `params` would be a reserved keyword that couldn't be used in state?

**Comment by yoshuawuyts** [comment]
@contra very good point; it def should be - so yes.

**Comment by contra** [comment]
@yoshuawuyts How would that work with non-object states?  ( https://github.com/yoshuawuyts/choo/issues/23 )

Not against it, but it might add some extra complexity to save one function param (or destructure).

**Comment by timwis** [comment]
`params` would be in the `app` namespace, like [`location`](https://github.com/yoshuawuyts/choo/blob/master/index.js#L204), so you should be able to use it in other models like you normally would, no?

**Comment by yoshuawuyts** [comment]
So state would always be an object; #23 refers to having non-objects as keys on the state; e.g. being able to do:
```js
app.model({
  namespace: foo,
  state: [ 'bin', 'bar', 'baz' ]
})
// yields state of: { foo: [ 'bin', 'bar', 'baz' ], params: {} }
```
The implication of #23 is, however, that non-namespaced state must always be an object that can be merged with the existing state. I think the overhead of having `state.params` should be manageable this way; both technically and for the mental model.

As per #82 `choo` would then provide two additions to the state: `state.location` and `state.params`.

**Comment by contra** [comment]
@yoshuawuyts Ah sorry, misunderstood where you wanted that to go. LGTM 💯

**Comment by yoshuawuyts** [comment]
Closing as 3.0 is imminent; wanna make sure all issues are taken care of. Releasing soooon™ :sparkles:
