### ISSUE TITLE
prev.location.params not being set

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#354]
### Expected behavior
After the first tick (when `prev` would be `null`), `prev.location.params` should be an object containing the previous `params`.

### Actual behavior
`prev.location.params` is always an empty object

### Steps to reproduce behavior
```javascript
const choo = require('choo')
const html = require('choo/html')

const app = choo()

app.model({
  state: { world: 'earth' },
  reducers: {
    updateWorld: (state, data) => ({ world: data })
  }
})

const View = (state, prev, send) => {
  console.log(state, prev)
  return html`
    <main>
      Hello, ${state.world}
      <button onclick=${onClick}>Update world</button>
    </main>
  `
  function onClick (e) {
    send('updateWorld', 'mars')
  }
}

app.router(['/:name', View])

const tree = app.start()
document.body.appendChild(tree)
```

![screen shot 2016-12-11 at 15 15 21](https://cloud.githubusercontent.com/assets/761444/21082976/eb366062-bfb4-11e6-96f9-558134451122.png)

^ the object on the left is `state`, the object on the right is `prev`. Notice that on the right, `params` is an empty object, despite there being a param in the `href` above it.

**Comment by yoshuawuyts** [comment]
Lol oops
