### ISSUE TITLE
Failing test in v4

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#357]
The tests in `freeze.js` fail because they have a router that doesn't return anything, and [this line](https://github.com/yoshuawuyts/choo/blob/master/index.js#L68) expects them to return something (a dom element).

Yosh proposed either `if (tree) { ... }` or `assert.ok(tree, 'tree should exist')`, recommending the latter. With the latter, the tests will still fail, so the question is: do we always expect the router to return something? If so, is it always an element?

**Comment by aknuds1** [comment]
A freeze test fails for me also due to `TypeError` being thrown upon modifying a frozen object. See my PR #364.

**Comment by yoshuawuyts** [comment]
Should be fixed now thanks to #360 also (:
