### ISSUE TITLE
Querystring not parsed when clicking on link

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#361]
### Expected behavior
Clicking on an `<a href="/foo?bar=baz">` should set `state.location.search` to `{bar: 'baz'}` (object)

### Actual behavior
`state.location.search` is set to `?bar=baz` (string)

### Steps to reproduce behavior
Add a link like the above to your page, then inspect the action that's sent using choo-log or a console.log.

I believe I've diagnosed the problem. The fix lies entirely in sheet-router, but it's pretty closely tied to the way choo uses sheet-router, so I thought I'd post it here.

Choo uses [sheet-router/href](https://github.com/yoshuawuyts/sheet-router/blob/master/href.js) as a subscription, firing whenever someone clicks an `<a>` and overriding its functionality. Href constructs an object. That object eventually gets passed back to sheet-router/create-location, which would normally parse the querystring if given a string, but since it was given an object, it just [applies updates directly](https://github.com/yoshuawuyts/sheet-router/blob/master/create-location.js#L29-L36) to it, failing to parse `search`.

**Comment by yoshuawuyts** [comment]
fixed in `sheet-router@4.1.3` :tada:
