### ISSUE TITLE
Since Choo 4 example counter vanilla.js bug

### ISSUE THREAD

**Issue by zckrs** [yoshuawuyts/choo#363]
### Expected behavior
The example should increment or decrement one by one.

### Actual behavior
In fact counter is incremented with strange value
![gifrecord_2016-12-14_122045](https://cloud.githubusercontent.com/assets/3020368/21180131/dccd3af6-c1f7-11e6-97e4-015a4477981c.gif)

### Steps to reproduce behavior
Just run https://github.com/yoshuawuyts/choo/tree/master/examples/vanilla

**Comment by aknuds1** [comment]
Could this be rectified by https://github.com/yoshuawuyts/nanotick/pull/6?

**Comment by zckrs** [comment]
:+1:  yeah fixed.

**Comment by yoshuawuyts** [comment]
yay! :tada: - sorry about the regression (:

**Comment by zckrs** [comment]
Np. The fix was quick 😄
