### ISSUE TITLE
Error when trying the tutorial: sheet-router: tree must be an array

### ISSUE THREAD

**Issue by dmitriz** [yoshuawuyts/choo#369]
### Expected behavior
App expected to run in the browser.
Other files run without problems.

### Actual behavior
When trying to run with `index.js` as described in 
https://yoshuawuyts.gitbooks.io/choo/content/02_your_first_app.html
getting the error in browser console:
```
assert.js:59 Uncaught AssertionError: sheet-router: tree must be an array
```

### Steps to reproduce behavior
Following the exact instructions in
https://yoshuawuyts.gitbooks.io/choo/content/02_your_first_app.html

Reduced to the simplest form:
```
const choo = require('choo')
const html = require('choo/html')
const app = choo()

app.model({
  state: {}
})

const view = (state, prev, send) => {
  return html``
}

app.router((route) => [
  route('/', view)
])

const tree = app.start()
document.body.appendChild(tree)
```

Still getting the error in the console

**Comment by dmitriz** [comment]
I was able to fix the problem by changing the router declaration to
```
app.router(
  ['/', view]
)
```
Perhaps the router expects an array rather than function?

**Comment by ebuckthal** [comment]
You are correct; the handbook is outdated. The recent update (v4.0) also updated the router module, [sheet-router](https://github.com/yoshuawuyts/sheet-router), to use the new syntax. The documentation in the choo README is up-to-date and I believe all of the examples in this repository are updated. 😺

**Comment by dmitriz** [comment]
How about the example here:
https://github.com/yoshuawuyts/sheet-router#virtual-dom-example
This defines `h`:
```
const h = require('virtual-dom/h')
```
Then `h` appears as unused arg here:
```
const router = sheetRouter([
  ['/foo/bar', (params, h, state) => html`<div>hello world!</div>`]
])
```
Very confusing!

**Comment by yoshuawuyts** [comment]
Oops yeah sorry - we haven't updated the handbook yet, and looks like we mightve missed an example on sheet-router, we should fix that. PRs would be very welcome!

**Comment by timwis** [comment]
[Fixed](https://github.com/yoshuawuyts/choo-handbook/pull/43) thx!
