### ISSUE TITLE
First argument of start() is not optional

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#37]
The [docs](https://github.com/yoshuawuyts/choo/#links) suggest you can pass options as the first parameter to `start`, ie. `app.start({ href: false })`, but doing so throws the following errors:

`Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'`
`Uncaught TypeError: rootId.replace is not a function` 

It appears to be because [this line](https://github.com/yoshuawuyts/choo/blob/master/index.js#L55) begins to make the first argument optional, but [this line](https://github.com/yoshuawuyts/choo/blob/master/index.js#L98) uses the second arg as if it were the first.

Happy to submit a PR to fix this, but can't do it right this second, so just wanted to post the issue in the meantime.

**Comment by yoshuawuyts** [comment]
yeah you're right - PR welcome! Thanks for catching that :sparkles;
