### ISSUE TITLE
My tiny webapp made with choo, merry, and bankai

### ISSUE THREAD

**Issue by MattMcFarland** [yoshuawuyts/choo#383]
First: sorry if this isn't the place to post but I wanted to get the word out and I figured this would be a good channel to share a webapp I made with choo!

I released a webapp that generates images with player stats for a game called Battlefield 1 - when you send your request it checks leveldb cache first, if not there it falls back on a redis cache, and lastly it falls back on a slow 3rd party API. The caching is for 24 hours and it seems to run very fast (so far) - Its running on nodejs using the merry framework which is a light alternative to something like express. It also uses choo-js on the front-end and bankai to dynamically bundle the clientside code before serving it. Overall it was a blast to make and I plan on blogging more about how it was made and steps I went through, along with the source. For now you can check it out here: https://bf-swag.herokuapp.com/

**Comment by marlun** [comment]
Do you have a link to the source code of this project? I'm interested to see the code, I don't care about Battlefield 😜

**Comment by MattMcFarland** [comment]
https://github.com/MattMcFarland/bf-swag

**Comment by yoshuawuyts** [comment]
:D yay!

**Comment by yoshuawuyts** [comment]
Thanks for sharing!
