### ISSUE TITLE
Router usage

### ISSUE THREAD

**Issue by delvedor** [yoshuawuyts/choo#386]
Hi guys! I'm loving this framework, many compliments!

Unfortunately at the moment I'm experiencing a strange problem, I cannot make the router work.
This is my code:
```js
'use strict'

const choo = require('choo')
const html = require('choo/html')

const view1 = (state, prev, send) => {
  return html`<h1>Hello!</h1>`
}

const view2 = (state, prev, send) => {
  return html`<h1>World!</h1>`
}

const app = choo()
app.router([
  ['/', view1],
  ['/world', view2]
])

const tree = app.start()
document.body.appendChild(tree)
```
If I go into the brawser at the `url` everything is ok, If I go to `url/world` I get a 404. Even if I set a default route (I tried both *budo* and *bankai* to compile the code).
Probably I'm lost in a glass of water, can you help me?
Thanks!

**Comment by JRJurman** [comment]
Using budo, I was able to get it to work by passing in the option `--pushstate`. This causes budo to always serve index.html (and not 404). I don't know if there's a way for choo to expose the routes to choo, but what I've done in the past is have my build scripts build an index.html at each route (e.g. `/index.html`, `/hello/index.html`, `/world/index.html`)

I've run into this issue in React as well, not sure if this is the best solution, but meh, it works.

**Comment by delvedor** [comment]
Hi! Thank you for the answer.
I'd like to know which is the recommended solution and not the "but meh, it works." :stuck_out_tongue_winking_eye:

**Comment by brechtpm** [comment]
Haven't tried `bankai` yet, but in `budo` the recommended solution should be `--pushstate`.

**Comment by josephluck** [comment]
@delvedor - this isn't a choo specific issue, but an issue for single page apps in general. http://jaketrent.com/post/pushstate-webpack-dev-server/ there's a good article explaining how to use webpack dev server. 

Personally I've found `budo --pushstate` more than adequate during dev, and a simple express server catching all routes to serve index.html for production.

**Comment by delvedor** [comment]
Ok, I've tested what you are saying and it works, thank you a lot!

@yoshuawuyts maybe we can add to the docs a line about this?
I know that is not an issue related to choo itself, but can be useful to others like me that didn't know the issue :)
