### ISSUE TITLE
Enhancement: Fully freeze state trie

### ISSUE THREAD

**Issue by kumavis** [yoshuawuyts/choo#387]
`Object.freeze` only works on the top level object

```js
// given state = { substate: {} } 
state.explode = true // error!
state.substate.xyz = true // NO error!
```

consider using [deep-freeze](https://github.com/substack/deep-freeze) to recursively freeze the whole state tree

**Comment by yoshuawuyts** [comment]
@kumavis hmm, yeah maybe we should - good suggestion; I think it might be for the best perhaps

**Comment by yoshuawuyts** [comment]
This'd be a breaking change tho :v:

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
