### ISSUE TITLE
Syntax highlighting of template string views

### ISSUE THREAD

**Issue by jamen** [yoshuawuyts/choo#393]
Is there  editor plugins to add syntax highlighting to the HTML inside of template string views?  I tired searching in this README and in the issues, but found nothing.  It would be useful to catalog them.  I personally use Atom and was wondering if there is a plugin.

I'm aware there is other modules (e.g. `bel` and `yo-yo`) that would also benefit from these, so probably not named after choo itself.

For an example, GitHub actually seems to do this already:

![image](https://cloud.githubusercontent.com/assets/6251703/22242099/b579876a-e1e7-11e6-8a05-fb95d2b32632.png)

**Comment by yoshuawuyts** [comment]
https://atom.io/packages/language-babel has tagged template literal
extensions which you can use to highlight HTML / CSS in atom

**Comment by jamen** [comment]
Thank you!

**Comment by jamen** [comment]
@yoshuawuyts Hmm, it didn't seem to work out of the box.  I tried looking in settings but didn't find anything.  What do you mean by extensions?

**Comment by jamen** [comment]
Never mind, I found big section in README on it.

**Comment by jbucaran** [comment]
Nice! I haven't been able to find a decent equivalent for vscode 🤔

**Comment by davidmarkclements** [comment]
@jbucaran see https://github.com/Microsoft/vscode/issues/2000

**Comment by marlun** [comment]
For vim there's https://github.com/Quramy/vim-js-pretty-template havn't gotten it to work very well though.
