### ISSUE TITLE
Confusing docs on passing sheet-router opts

### ISSUE THREAD

**Issue by ruudud** [yoshuawuyts/choo#396]
The [current docs](https://github.com/yoshuawuyts/choo#tree--appstartopts) states that it is `app.start()` that needs to be passed an opts object containing router config:
```javascript
app.start({ history: false, href: false });
```

However, currently these needs to be passed to the "constructor" function to work:
```javascript
var app = choo({ history: false, href: false });
```

**Comment by yoshuawuyts** [comment]
Oh yeah we changed that in v3 or v4. PR welcome!
