### ISSUE TITLE
Choo seems to be throwing away events during selenium testing

### ISSUE THREAD

**Issue by vaughansharman** [yoshuawuyts/choo#416]
### Expected behavior
When I run selenium tests against a choo application I expect interactions with the browser to no be lost

### Actual behavior
When running selenium tests against the browser, characters are lost, it seems that choo cannot keep up with the rate at which events are being fired. I end up with "non deterministic" results. For example sometimes "username" becomes "usnme" or "usere" etc...

I solved this issue buy putting a cleep in the selenuim tests to sleep a couple of nano seconds between sending each character to the browser

Whilst in the real world we probably would not expect a user to type as quickly as a selenium test this seems like a firly common requirement for developers and must be affecting others too

### Steps to reproduce behavior
Run selenium tests against a page with a text input box that updates a state model. When the test is run at full speed some characters are lost.

**Comment by aknuds1** [comment]
Could this be because of Choo's asynchronous handling of reducers?

I think @yoshuawuyts in general recommends reading text input directly from the DOM element since the state isn't synchronously updated.

**Comment by josephluck** [comment]
@aknuds1 - this isn't a viable work around since the state should be the source of truth, not the DOM. In some cases, you will want to validate on keypress etc, so having an up-to-date representation of state in your model is the best approach.

**Comment by aknuds1** [comment]
@josephluck Just referring to what @yoshuawuyts has said before, wrt. why yo-yo avoids applying incoming undefined `input` values when diffing the DOM.

**Comment by josephluck** [comment]
Right now, my approach is to debounce the reducer that updates the state bound to the input by a really short amount. Works in selenium tests and in the browser AFAIK.

**Comment by yoshuawuyts** [comment]
Closing because `choo@5` will introduce a new API. See #425 for the merged PR. Thanks!
