### ISSUE TITLE
Route paths with multiple slashes not loading

### ISSUE THREAD

**Issue by gitnix** [yoshuawuyts/choo#418]
I have:  
```
['/', List]
['/page/:pageNumber', List]
```
 in my router. If I navigate to '/' I can click the links I have set up such as
```
html`<a href="/page/${ pageNumber + 1 }">More</a>`
```
to change the page number and have the route change to 'blahblah/page/2' in the address bar. However, I can not seem to directly navigate to any route with multiple slashes. I get a 404 if try to go to the page directly.

I am serving this with budo locally. I understand this is probably something more to do with budo/sheet-router. I couldn't come up with anything after perusing through the sheet-router and budo docs. I was wondering if someone could point me in the right direction? Thanks.

**Comment by josephluck** [comment]
Hey, you probably need to use budo --pushstate option. On 19 Feb 2017 06:22, Ryan Eppers <notifications@github.com> wrote:I have:
['/', List]
['/page/:pageNumber', List]

in my router. If I navigate to '/' I can click the links I have set up such as
html`<a href="/page/${ pageNumber + 1 }">More</a>`

to change the page number and have the route change to 'blahblah/page/2' in the address bar. However, I can not seem to directly navigate to any route with multiple slashes. I get a 404 if try to go to the page directly.
I am serving this with budo locally. I understand this is probably something more to do with budo/sheet-router. I couldn't come up with anything after perusing through the sheet-router and budo docs. I was wondering if someone could point me in the right direction? Thanks.

**Comment by gitnix** [comment]
Hey @josephluck. Ya, I saw your previous post before I made mine here. Unfortunately '--pushstate' does not change the behavior :( I am following this repo that is listed on the choo demos page to help me learn choo: https://github.com/kvnneff/hackernews-choo. I am rewriting the outdated v3 parts in v4. My package.json is the same listed as the one in this repo with all the dependencies at their newest versions. All routes work if I try, say, '/this', or '/that'. However, if I try 'this/that' I get the 404 (I can still. Thanks for the response. Any other probable possibilities you can think of? I can provide more details/ share the code if necessary. Thank you.

**Comment by josephluck** [comment]
Yeah go ahead and share the code, I can take a lookOn 19 Feb 2017 19:46, Ryan Eppers <notifications@github.com> wrote:Hey @josephluck. Ya, I saw your previous post before I made mine here. Unfortunately '--pushstate' does not change the behavior :( I am following this repo that is listed on the choo demos page to help me learn choo: https://github.com/kvnneff/hackernews-choo. I am rewriting the outdated v3 parts in v4. My package.json is the same listed as the one in this repo with all the dependencies at their newest versions. All routes work if I try, say, '/this', or '/that'. However, if I try 'this/that' I get the 404 (I can still. Thanks for the response. Any other probable possibilities you can think of? I can provide more details/ share the code if necessary. Thank you.

**Comment by gitnix** [comment]
Thanks for offering to check. I found out the `--base` option is also needed for nested paths to work correctly. Everything works as intended now :) Again, I appreciate you following up with me.

**Comment by josephluck** [comment]
No worries, glad you got it sorted!On 21 Feb 2017 06:50, Ryan Eppers <notifications@github.com> wrote:Thanks for offering to check. I found out the --base option is also needed for nested paths to work correctly. Everything works as intended now :) Again, I appreciate you following up with me.
