### ISSUE TITLE
Is state immutable in a reducer?

### ISSUE THREAD

**Issue by toddself** [yoshuawuyts/choo#44]
I've been considering state to be immutable within the context of a reducer -- it looks like the `state` you get in the arguments is generated with `xtend`, right?

I'm wondering through, what is the best way to provide a new state for an array?

I've been doing something similar to:

```js
const data = state.data.slice(0)
data.splice(data.findIndex(r => r.id == action.id), 1)
return {data: data}
```

In a reducer, but it feels odd to be creating a clone of the array there, but it feels odd to do:

```js
state.data.splice(state.date.findIndex(r => r.id === action.id), 1)
return {data: state.data}
```

**Comment by yoshuawuyts** [comment]
At the moment objects can be mutated and we're not guarding against that. It's not recommended to do so, and I think not having it set in code isn't good. A possible option to guard against that might be a recursive `Object.freeze()` before sending state objects off into the app, but that's up for debate.

I think your first example should be the way to go:
```js
const data = state.data.slice(0)
data.splice(data.findIndex(r => r.id == action.id), 1)
return {data: data}
```

Does this answer your question?

**Comment by toddself** [comment]
It does.  I didn't see `Object.freeze` in the code, but was trying to get into the mindset -- mutating state within a reducer or an effect feels like a side-effect, but wanted to know if there were any guards from being able to do so.

Thanks!

**Comment by yoshuawuyts** [comment]
ps this might be related to https://github.com/sethvincent/send-action/issues/6 also
