### ISSUE TITLE
process.env.NODE_ENV for example app

### ISSUE THREAD

**Issue by zigomir** [yoshuawuyts/choo#444]
### Expected behavior
`app.use(logger())` would execute in production build.

### Actual behavior
Seems like logger is used in production build according to console.

### Steps to reproduce behavior
`npm run build` inside `example` directory and serve `dist` directory.

I remember once README.md included whole lot of browserify transforms for production build. I don't know how `bankai` works but I'd assume `--optimize` should somehow strip out `if (process.env.NODE_ENV !== 'production') {` stuff or it should be explained what this is doing and how.

**Comment by yoshuawuyts** [comment]
Oh yeah oops we haven't included `envify` into `bankai` yet. Opening an issue for it there haha

**Comment by yoshuawuyts** [comment]
Issue created, closing it here. Thanks for reporting!

**Comment by zigomir** [comment]
Awesome, thanks for such quick response!
