### ISSUE TITLE
Html var into html

### ISSUE THREAD

**Issue by yudao** [yoshuawuyts/choo#445]
Hi,

First I've updated my code with the 5.0.4 api version. Very good work! 

### Expected behavior
I want to include in my template string a HTML string from a var.

### Actual behavior
The html output is a string so by example my img tag is literally outputted as string and no image is shown.

```html
"coucou <img class="emojione" alt="🙂" src="//cdn.jsdelivr.net/emojione/assets/png/1f642.png?v=2.1.2"/>"
```

### Steps to reproduce behavior
Example:
```js
import html from 'choo/html';
import emojione from 'emojione_minimal';

emojione.ascii = true;

module.exports = (input, emit) => {
  return html`
    <div>${emojione.shortnameToImage(input.text)}</div>
  `;
};
```

I've tried with the html() function instead of html`` but bel send an error:
```js
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'emojione"' is not a valid attribute name.
```
I've tried to include my emojione return value into an another var but bel send always a setAttribute error.

Thanks for your help.

Yu.

**Comment by YerkoPalma** [comment]
Are you using `yo-yoify`? I have been in a [similar error](https://github.com/shama/bel/issues/62) before, but I'm not sure if it is related.

**Comment by yudao** [comment]
Thanks @YerkoPalma.

I've already seen your issue and help me to find the html() function instead of html``.

But I'm not using yo-yoify. Only choo coupled with my front builder [Brunch](http://brunch.io/).

**Comment by yoshuawuyts** [comment]
Interesting - it seems you're also using `import` which probably means you're running some sort of compiler right? Perhaps babel? - I'm not sure what they're up to, but my guess is that's messing something up.

If you have a repro we could maybs try and take a look?

**Comment by greggraf** [comment]
@yudao -  I saw an error similar to yours when passing a string directly to  `html()` .

It worked when I passed an array of strings as the first argument, which is what tagged templates literals do.

Does this work?
 
```js
module.exports = (input, emit) => {
  return html(["<div>", emojione.shortnameToImage(input.text), "</div>"]);
};
```

**Comment by yudao** [comment]
@greggraf Sorry for the delay. Awesome tip ! it's working like a charm !

Thanks all for your help!

Yu.
