### ISSUE TITLE
Unused variables?

### ISSUE THREAD

**Issue by mantoni** [yoshuawuyts/choo#451]
I was wondering while reading [the sources here](https://github.com/yoshuawuyts/choo/blob/5b4083adfd205e0db30d81d4bf9b256b808b2946/index.js#L52):

```js
tree = router(createLocation(), state, emit)
```

I don't see where `state` and `emit` are being used in the router. Or am I reading it wrong?

**Comment by aknuds1** [comment]
Looks to me as if the second and third arguments are superfluous too, as [nanorouter](https://github.com/yoshuawuyts/nanorouter) only requires a route argument does it not?

**Comment by yoshuawuyts** [comment]
Yup, think so
