### ISSUE TITLE
Initial state

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/choo#464]
### Expected behavior
Should be easy to set an initial state for choo app.

### Actual behavior
Not sure how to set it up, without using events (like the DOMReady event)

### Steps to reproduce behavior
I expected that something like this would set up an initial state

```js
const choo = require('choo')
const sf = require('sheetify')
const mainView = require('./views/main')
const notFoundView = require('./views/not-found')

sf('tachyons')

const app = choo()

app.use(init)
app.route('/', mainView)
app.route('/404', notFoundView)
app.mount('body')

function init (state, emitter) {
  state = {
    username: 'Yerko Palma',    
    initial: true
  }
}
```

But that doesn't work.

---
Now what would be the best option IMO is something like this

```js
const app = choo({
  state: {
    username: 'Yerko Palma',    
    initial: true
  }
})
```

for that the only update that choo would need would be in [this line](https://github.com/yoshuawuyts/choo/blob/master/index.js#L29) something like this

```js
var state = opts.state || {}
```

What do you think?

**Comment by YerkoPalma** [comment]
I have played with this a bit, and it isn't as simply as it looks. Adding an option for default state, set the state but it isn't persisted, at least not in the todo example. Will keep looking at it.

**Comment by yoshuawuyts** [comment]
You can't override the object, you need to set values on the existing
object. Or use xtend / Object.assign - hope that helps!

**Comment by YerkoPalma** [comment]
Yeah, I realized that my `init` function should be like this

```js
function init (state, emitter) {
  state = Object.assign(state, {
    username: 'Yerko Palma',    
    initial: true
  })
}
```

But my other option, modifying choo state declaration, is not working. Do I have to use `Object.assign` there too?

**Comment by yoshuawuyts** [comment]
Modify a value, then call emit('render')

**Comment by yoshuawuyts** [comment]
Think this should be solve - closing!
