### ISSUE TITLE
Can't edit input fields from the middle

### ISSUE THREAD

**Issue by bcomnes** [yoshuawuyts/choo#475]
When you try to edit input fields from the middle of whatever string you have int it, it resets the cursor to the end.  I'm guessing this has something to do with the change over to nanomorph.
![choo field bug](https://cloud.githubusercontent.com/assets/166301/25016410/b881a894-2034-11e7-8eed-bc7e92f032ff.gif)

**Comment by bcomnes** [comment]
Perhaps a better way to describe this is:

Starting in choo5/nanomorph, If you call render while editing a field, it resets cursor position.

**Comment by yoshuawuyts** [comment]
Published nanomorph `v4.0.4`. Can you confirm that this fixes your issues. You mentioned that the range slider reset no longer works - can you maybs open an issue for that? Thanks!

**Comment by bcomnes** [comment]
Yeah. Just getting started here this morning.

**Comment by yoshuawuyts** [comment]
cool!

**Comment by cideM** [comment]
Any ETA when nanomorph `v4.0.4` will make it into a Choo release? Because as far as I can see the current Choo `v5.4.0` still uses `4.0.0` and therefore this issue persists with the current Choo version

**Comment by bcomnes** [comment]
Choo depends on `^4.0.0` so that should include `v4.0.4`

The trick is to set the value of the input field in your bel template (you could use state or anything else).

![screen shot 2017-05-15 at 4 39 11 pm](https://cloud.githubusercontent.com/assets/166301/26083879/29b43e48-398d-11e7-8315-477e9e85f1c9.png)

If you need to decouple your field from render cycles you can use nanocomponent or cache-component

**Comment by cideM** [comment]
The view function that renders the input is
```
  h`<input
      class='w-75 ba b--moon-gray pa2 f3'
      id=${options.id}
      name=${options.name}
      type=${options.type || 'text'}
      value=${options.value}
      placeholder=${options.placeholder || ''}
      onkeyup=${options.onKeyUp || noOp}
      onclick=${options.onClick || noOp}
      onblur=${options.onBlur || noOp}
      onchange=${options.onChange || noOp}
      oninput=${options.onChange || noOp}
      required=${options.required || false}
  >`
```
It gets its parameters like so:
```
        Input({
          id: 'category',
          name: 'category',
          type: 'text',
          value: category,
          placeholder: 'Dinner',
          onBlur: onKeyUp,
          onChange: onKeyUp,
          required: true
        })
```

And upon e.g., a `keyup` event, this is fired
```
  const onKeyUp = (e: SyntheticInputEvent) => {
    emit(SET_VALUE, ({ key: e.target.id, value: e.target.value }))
  }
```

This causes the cursor to jump to the end, whenever I edit something in the middle, as shown in the first post.

**Comment by cideM** [comment]
Thanks for the info about SemVer, you learn something new every day :)

I guess my issue was that I was calling `render` on every `keyup` event. Maybe not how it's supposed to be done?
```
  emitter.on(SET_VALUE, (data: Object) => {
    state.currentPurchase[data.key] = data.value
   emitter.emit('render') <---- commenting out this line solves the problem
  })
```
`SET_VALUE` here is called on every e.g., `keyup`
