### ISSUE TITLE
Multiple choo components on a page

### ISSUE THREAD

**Issue by toddself** [yoshuawuyts/choo#49]
Just was futzing around with testing and realized that since choo controls it's domain via the addition of `#choo-root` on the element and the fact that everything is initialized and kept in the choo closure, it makes it impossible to have more than one choo component per page.

IMO it would be ideal if you could create multiple choo-owned objects per page, each with their own model and part of the DOM (you could add a data attribute with a randomized id and move choo into a "factory" of sorts (either through `new` or returning an `Object.create` etc)

**Comment by timwis** [comment]
I recall from the code that `#choo-root` is [only the default name of the container](https://github.com/yoshuawuyts/choo/blob/master/index.js#L62). You should be able to have multiple components on a page via:

```javascript
const app1 = choo({ name: 'app1' })
const app2 = choo({ name: 'app2' })
```

**Comment by toddself** [comment]
Ah. Somehow missed that.  It means you also have to namespace your model it seems? Thanks @timwis

**Comment by timwis** [comment]
Nope - I don't believe `name` and `namespace` are connected.

**Comment by toddself** [comment]
I mean namespacing for issues like this:

```js
const choo = require('choo')

const app1 = choo({name: 'app1'})
const app2 = choo({name: 'app2'})

app1.model({
  state: {
    data: 'app1'
  },
  reducers: {
    update: (action, state) => ({data: action.value})
  }
})

app2.model({
  state: {
    data: 'app2'
  },
  reducers: {
    update: (action, state) => ({data: action.value})
  }
})

function app1main (params, state, send) {
  return choo.view`<button onclick=${(evt) => send('update', {value: 'app1main'})}>${state.data}</button>`
}

function app2main (params, state, send) {
  return choo.view`<button onclick=${(evt) => send('update', {value: 'app2main'})}>${state.data}</button>`
}

app1.router((route) => [
  route('/', app1main)
])

app2.router((route) => [
  route('/', app2main)
])

const tree1 = app1.start()
const tree2 = app2.start()

document.body.appendChild(tree1)
document.body.appendChild(tree2)
```

If you click on the second button, it changes the state of the first button.  Just adding a namespace to each new call to `choo#model` and the `send` events doesn't rectify this situation. 

```js
const choo = require('choo')

const app1 = choo({name: 'app1'})
const app2 = choo({name: 'app2'})

app1.model({
  state: {
    data: 'app1'
  },
  reducers: {
    update: (action, state) => ({data: action.value})
  }
})

app2.model({
  state: {
    data: 'app2'
  },
  reducers: {
    update: (action, state) => ({data: action.value})
  }
})

function app1main (params, state, send) {
  return choo.view`<button onclick=${(evt) => send('update', {value: 'app1main'})}>${state.data}</button>`
}

function app2main (params, state, send) {
  return choo.view`<button onclick=${(evt) => send('update', {value: 'app2main'})}>${state.data}</button>`
}

app1.router((route) => [
  route('/', app1main)
])

app2.router((route) => [
  route('/', app2main)
])

const tree1 = app1.start()
const tree2 = app2.start()

document.body.appendChild(tree1)
document.body.appendChild(tree2)
```

Still only ever effects the first button.

**Comment by toddself** [comment]
This actually seems to be a bug in choo.  If I look at the DOM I get:

![image](https://cloud.githubusercontent.com/assets/193412/16174584/c0ef6faa-357c-11e6-92ef-1383cf39f607.png)

So regardless of what I'm passing in for `name` it doesn't seem to change how choo is identifying the DOM nodes?

**Comment by toddself** [comment]
Ah!

Upon closer inspection, you need to do:

```js
const app1 = choo()
const app2 = choo()
app1.start({name: 'app1'})
app2.start({name: 'app2'})
```

Passing in just the string as the name does not work there, but it might be more discoverable if it did?  Or perhaps it should be an argument when you're invoking `choo` like @timwis has in his example?

**Comment by toddself** [comment]
#52 resolves the final question in this thread :)
