### ISSUE TITLE
Access an immutable version of state via subscribers

### ISSUE THREAD

**Issue by toddself** [yoshuawuyts/choo#50]
I mentioned this on irc earlier today.  On-demand, synchronous access to the data in the state isn't 100% necessary in probably 99% of use-cases, but it does make it easier to work with a choo component from the outside.

Example: if someone wanted to access part of the state object (i.e. the data driving a boxcar view) in order to serialize it somewhere else:

```js
const emitter = require('events')()
const app = choo()
app.model({
  state: {
    data: [],
    moreState: [].
    evenMore: {}
  },
  subscriptions: [
    (send, state) => emitter.on('getData', (cb) => cb(null, state.data)
  ]
})
return emitter
```

Then someone could do:
```js
boxcar.emit('getData', (err, data) => serializeData(data))
```

**Comment by yoshuawuyts** [comment]
I feel this might conflict with https://github.com/yoshuawuyts/choo/issues/32; if not programmatically, definitely in the mental model. Perhaps what could be an option is to expose [send-action](https://github.com/sethvincent/send-action) under the hood as `app._send` or something for the 1% of the time people are interested in this - don't even feel it's needed to document

**Comment by toddself** [comment]
Yeah I gave this some more thought last night. It's a pain to not be able to access state ever, but it's for the better.  It just means if I want some sort of serialization I'm going to have to create it as an option, which keeps things MUCH neater as it is.

**Comment by toddself** [comment]
Although it does make testing a little more difficult.  I ended up doing something like this:
https://github.com/toddself/boxcar/blob/master/test/grid-data.spec.js#L31-L72

I'm still not sure it's "right", but it works :)

**Comment by timwis** [comment]
Agreed -- being able to check the state from outside would make testing much easier. For example, if you simulate a user interaction on your view and then want to check that the state was updated properly. You could mock the `state` and `send` that you pass to your view but if you could access your application's state from outside of it, you could test the entire interaction.

**Comment by yoshuawuyts** [comment]
@timwis I reckon https://github.com/yoshuawuyts/choo/issues/15 might help solve that? - hook up a listener to `*`, mount a view, call an action, validate state inside the listener. Does that work you think?

**Comment by timwis** [comment]
@yoshuawuyts I think so.. but that really depends on whether `*` is called before or after the reducers finish.

**Comment by yoshuawuyts** [comment]
@timwis oh dammit, you're right - hmmm, well if the hook is in a reducer that's called only after all other reducers are done... it should work I reckon

**Comment by timwis** [comment]
Yes, though, one other thought -- what if the action you're testing fires multiple `send()` calls? For instance, `send('fetch')` triggers an effect which executes `send('isFetching', false)` and `send('receiveData')`. The `*` reducer would be called 3 times there. Even twice for reducers alone.

**Comment by yoshuawuyts** [comment]
Yup, but then you can check for all three calls and see the state - or know there will be three calls and only check the third. I reckon it's good ^__^
