### ISSUE TITLE
Test utilities

### ISSUE THREAD

**Issue by graforlock** [yoshuawuyts/choo#500]
`choo` seems nice and dandy but testing is a bit of a pain.

Where in React you would typically compare JSX with another JSX and have a match, in choo it does not seem so straightforward after for example comparing expected `choo/html` output with real component output, one needs to make either creative regexes or compare some DOM selector results. That due to comparing ES6 string templating, where spaces make it very inconsistent.

Is there plans for some testing utilities that would make it out of the box? 

For example (jasmine):

```javascript
expect(renderedMain.outerHTML).toEqual(
     html`
     <div>Hello</div>
     `.outerHTML
)
```

Will most of the times fail or be difficult to use due to whitespace inconsistency and stuff. With comparing DOM objects its also not too nice, as it then is much more abstracted away from the HTML markup (in case of differences).

**Comment by graforlock** [comment]
It seems like `jest` in version 20.0 does a nice job. For all, make sure its not 19.0 - this version doesn't support serialising native DOM.

**Comment by yoshuawuyts** [comment]
For UI testing there'd ideally there'd be a DOM string comparison library that could work with `tape`, similar to [spok](https://github.com/thlorenz/spok).

But not all testing is UI testing; I'd argue UI testing has the lowest priority - whereas unit testing logic is a bit more pressing. To do this you can take any function that is passed to `.use()` and call it with a custom state object + event emitter instead. You can then test the full range of behavior and listen to the events it emits. This should provide a good separation of concerns. :sparkles:

I hope this answers your question!

**Comment by graforlock** [comment]
Thanks.

I meant not so much UI but rather interaction testing; in my experience units rarely do fail on their own, and I what mean unexpectedly - which is the most valuable case for testing.

Although I agree that tape is a nice little thing, for ES6 and DOM is a bit of pain to work with in terms of configuration.  It turns to be a bit time consuming and expensive. Jest seems to work perfectly as of now, especially with automating automatic unit tests and contract changes.
