### ISSUE TITLE
Does not work with any of the map APIs (re-rendering incompatibility)

### ISSUE THREAD

**Issue by graforlock** [yoshuawuyts/choo#507]
### Expected behavior
With the library like ```leafletjs``` or  google maps API, ```choo```  should render a geo map and then update (re-render) it without any problem.

### Actual behavior
Upon emitting ```render``` with updated coordinates (latitude and longitude), every map implementation dies and then displays blank container or , alternatively,  empty, grey map. Tested with:

1. Leaflet
2. Google Maps
3. Mapbox GL

It results in the same outcome.

### Steps to reproduce behavior

Example code (map component):
```javascript
import html from 'choo/html';

export default ({latitude = 51.505, longitude = -0.09, zoom = 18, markers = []},
    emit) => {
    const geoMap = html`<div id="map" style="height: 380px"></div>`;
    if (typeof L !== 'undefined') {
            const map = L.map(geoMap).setView([latitude, longitude], zoom);
            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
                maxZoom: zoom,
                id: 'mapbox.streets',
                accessToken: 'apiTokenHere'
            }).addTo(map);    
    }
    return geoMap;
};
```

**Comment by graforlock** [comment]
It may not be related I am not sure what's causing this issue. If its not diffing algorithm issue, than its probably worth closing.

**Comment by graforlock** [comment]
Just found its unrelated to choo's render!

**Comment by graforlock** [comment]
Yup, the rerender of anything apparently kills all maps. 

There has to be a way not to do this as this makes geocoding impossible.

**Comment by yoshuawuyts** [comment]
Check out the example in https://github.com/yoshuawuyts/nanocomponent, you
need to make sure that the DOM element is not recreated on each render,
nanocomponent (and https://github.com/yoshuawuyts/microcomponent) help with
this (:

**Comment by graforlock** [comment]
Thats cool, but a bit low-level. Wouldn't it be much better to add/extend something in the API ? Some layer of abstraction.

Especially given that choo aims to be top-level framework at the tompost `body` level

**Comment by lvivier** [comment]
@graforlock the diffing module used by choo ([nanomorph](https://www.npmjs.com/package/nanomorph)) allows for this. You can override the `isSameNode()` method of an element to prevent nanomorph from replacing it:

```js
let el = bel`<div id='abc'>cache me ousside</div>`
el.isSameNode = function (target) { return target.id === 'abc' }
```

From the [caching DOM elements](https://www.npmjs.com/package/nanomorph#caching-dom-elements) section in the nanomorph docs:

> Sometimes we want to tell the algorithm to not evaluate certain nodes (and its children). This can be because we're sure they haven't changed, or perhaps because another piece of code is managing that part of the DOM tree. To achieve this nanomorph evaluates the .isSameNode() method on nodes to determine if they should be updated or not.

nanocomponent [overrides this method](https://github.com/yoshuawuyts/nanocomponent/blob/master/index.js#L80-L82) under the hood.

**Comment by graforlock** [comment]
You are right, its even on the forefront of github :) My bad
