### ISSUE TITLE
assert.equal() missing arguments missed by unassertify

### ISSUE THREAD

**Issue by DanWilkerson** [yoshuawuyts/choo#509]
### Expected behavior
`unassertify` should remove all assertions in the code

### Actual behavior
Call to `assert.equal` on https://github.com/yoshuawuyts/choo/blob/master/index.js#L120 isn't passed any arguments and appears to be missed by `unassertify`. This causes an exception when `app.toString()` is called.

### Steps to reproduce behavior
Build a Choo app that calls `.toString`, run `unassertify` on it, run the app.

**Comment by yoshuawuyts** [comment]
good catch, sorry about this :'(
