### ISSUE TITLE
How to prevent mounting/unmounting from DOM using microcomponent?

### ISSUE THREAD

**Issue by ojack** [yoshuawuyts/choo#511]
[Question] I am new to choo and trying to understand better. Not sure whether this has more to do with choo or with micro/nanocomponent.

### Expected behavior
Element is only mounted/unmounted from the DOM if it has changed.

### Actual behavior
Dom element is unmounted and remounted even though nothing has changed. Returning 'false' in update() method of microcomponent prevents render, but does not prevent mounting/unmounting from the DOM. 

### Steps to reproduce behavior
https://gist.github.com/ojack/2051c6443f4fa1a9565c868a178cbd07

**Comment by yoshuawuyts** [comment]
uh oh, this looks like a bug for sure

**Comment by yoshuawuyts** [comment]
Work being done in https://github.com/yoshuawuyts/microcomponent/pull/21

**Comment by juliangruber** [comment]
with a fresh npm install this should be fixed :)
