### ISSUE TITLE
svg use produces "multiple root elements must be wrapped in an enclosing tag" error

### ISSUE THREAD

**Issue by mfolkeseth** [yoshuawuyts/choo#514]
It seems strange to me that the following markup produces the `multiple root elements must be wrapped in an enclosing tag`error message:

```
return html`
      <div>
        <svg>
          <use xmlns:xlink="http://www.w3.org/1999/xlink" href="#reply"></use>
        </svg>
      </div>
    `;
```

**Comment by YerkoPalma** [comment]
I'm not clear if you say that this code _should_ get the error message or if it _is getting_ the error message and it shouln't.

**Comment by mfolkeseth** [comment]
Sorry, a bit unclear there. This code _is getting_ this error. I don't see why it does.

**Comment by yoshuawuyts** [comment]
Not on laptop right now so can't debug - sometimes this error is
incorrectly thrown because tags are closed when they shouldn't be - or a
trailing closing tag is added when it isn't needed. Could you try out a
variation of these? Thanks!

**Comment by YerkoPalma** [comment]
This is a bel issue not choo specific. and is not actually an issue, it happens to me when I had `<path></path>` in my svg, it fixed changing it to `<path />`. So, in your case it should fix with

```js
return html`
      <div>
        <svg>
          <use xmlns:xlink="http://www.w3.org/1999/xlink" href="#reply" />
        </svg>
      </div>
    `;
```

**Comment by mfolkeseth** [comment]
Thanks, that fixes my problem. I'll close this.
