### ISSUE TITLE
Handling new canvas elements

### ISSUE THREAD

**Issue by adedomin** [yoshuawuyts/choo#524]
### Expected behavior
New canvas dom elements will replace old canvas dom elements.

### Actual behavior
canvas tags only have attribute changes, such as id="" and causes breakage when the context the canvas tag points to is lost.

### Steps to reproduce behavior
create a canvas element, get canvas context, draw to it => load canvas' dom object into a view => create new canvas element and assign it to the previous canvas element's variable => emit('render') and redraw view.

I'll produce example code in a bit.

current workaround is to call something like 
`if (state.canvas) state.canvas.parentNode.removeChild(state.canvas)`
prior to assigning a new canvas.

I realize this might be "by design" and not fixable.

**Comment by yoshuawuyts** [comment]
Oh, interesting; so what you're saying is that morphing an old canvas will
not work but you must discard it instead?

I would imagine using https://github.com/yoshuawuyts/nanocomponent/ + a
proper setup and teardown step to achieve the right results, no?

**Comment by adedomin** [comment]
I suppose that's fair. thanks.
