### ISSUE TITLE
app.send() is not a function

### ISSUE THREAD

**Issue by sethvincent** [yoshuawuyts/choo#63]
In the readme the effects description implies that the `app.send()` method exists: https://github.com/yoshuawuyts/choo#appmodelobj

We should either revise that bit of the docs or attach `send` to `app`.

I found this writing some alternate link-catching code and wanted to send an action to update the state with the new location.

I was doing this just in an onclick event listener, but I _could_ do it in a subscription, and that's probably the recommended approach, rather than needing `app.send`.

**Comment by yoshuawuyts** [comment]
Hah yeah, the docs should be updated on that one; I'd rather not expose `send()` and `state` outside the application boundries, as it enables behavior that would break the pattern - going with `subscriptions` is def recommended here :sparkles:

**Comment by sethvincent** [comment]
:+1: agreed

**Comment by yoshuawuyts** [comment]
This should be fixed in the `3.0` docs - closing as release is imminent :sparkles:
