### ISSUE TITLE
browser support?

### ISSUE THREAD

**Issue by jescalan** [yoshuawuyts/choo#69]
Just curious, what does browser support look like for this library? Does it work everywhere out of the box? Does it require certain transforms to work in certain places? Are there old shitty versions of IE it definitely will not work in?

This would be a great thing to have in the readme as well, happy to PR it in if you want 👍

**Comment by yoshuawuyts** [comment]
Ahh yeah so this definitely ties into the work @toddself has been doing over in https://github.com/yoshuawuyts/choo/pull/46#issuecomment-226645328.

Out of the box this package only works in evergreen browsers (because template strings), but using [es2020](https://github.com/yoshuawuyts/es2020) and soon [yo-yoify](https://github.com/shama/yo-yoify) it should probably work in any browser that supports ES5 (which should be pretty much anything up from IE8/9 I reckon)

Having full test / browser coverage would def be great! PRs to help with that are _very_ welcome! I've been slacking on getting saucelabs up, but I'll get to that soon - I promise.

**Comment by jescalan** [comment]
Cool, thanks for the quick answer! Appreciate the great work you are doing here for sure. I'll dive in further if I have some time to do so 😁 

I might in the meantime just change the "is this production ready" section from "sure" to "not yet" -- you don't want to have someone start using this for a project only to realize it's not working in IE. As unfortunate as that dumb browser is, supporting it is still necessary for production projects 😭

**Comment by yoshuawuyts** [comment]
> I might in the meantime just change the "is this production ready" section from "sure" to "not yet"

haha, but the stability badge says "experimental" - like with any project we're improving as we go. I definitely feel more comfortable recommending choo for a new project than pretty much any alternative out there.

I think people can make good judgement calls: it's public knowledge the repo's only been around for six weeks, and being actively worked on. Picking it up right now might have a bit of breaking changes for `v3`, but actually choo's pretty good as is right now, there's even people using it for production stuff :sparkles:

If anything using `choo` is an investment in the future; there might be a few breaking changes, but you'll know that elements you create with `choo` / `yo-yo` / `bel` will be relevant as long as there's a DOM, and that's probably something worth investing in right now.

**Comment by jescalan** [comment]
Don't disagree with anything you're saying here, I just feel like it might make life easier for people if you just tell them upfront rather than asking them to read into badges and how long the repo has been around, etc to make their decision.

Saying that it doesn't work in IE doesn't mean that nobody should use the project, it just means that it _currently_ isn't production ready, which is important to know when starting a new project. Including even a rough estimate on when it will be ready in that section would be super helpful as well, but entirely understandable if that's not possible too.

💖

**Comment by toddself** [comment]
If you are compiling to es5 there is no reason it should't work in ie. I am working on testing my choo app back to ie 9. 

So its supported, but out of the box your browser has to support a latest version of the spec since it does rely on template tags and arrow functions. 

But if you are trying to support safari on desktop or mobile you'd need to do that for them as well.

**Comment by jescalan** [comment]
All I'm saying here is that it would be helpful to add this information to the readme. If you are using code that runs in the browser, something people look for and want to know is browser support.

**Comment by toddself** [comment]
@jescalan we are currently working on implementing browser tests which should help document some of this stuff.

First, the [README now](https://github.com/yoshuawuyts/choo#how-can-i-optimize-choo) talks about optimization.

However in the testing branch we make specific mention in the README that you should be using browserify and that if you need to support a non-es2020 runtime (fat arrows, template tags and const) you'll need to provide something to compile down to whatever your browser supports.

We are recommending [es2020](https://github.com/yoshuawuyts/es2020) for various reasons, but really, anything that can transform those three es2015/es6/eswhatever features into something the browser you're targeting supports, you should be good to go.

You can see the proposed changes in #86.  If you're still concerned or missing something, please let us know!

**Comment by toddself** [comment]
@jescalan closing this after the testing branch and explanation on what you'll need to do to support certain levels of browsers. Please let us know if you have any other concerns!

**Comment by jescalan** [comment]
Sounds good. Thanks for your great work guys!

**Comment by yoshuawuyts** [comment]
@jescalan ☺️

Live browser CI status can now be found on https://github.com/yoshuawuyts/choo#browser-test-status
