### ISSUE TITLE
Suggest compiling template strings beforehand

### ISSUE THREAD

**Issue by PaulBGD** [yoshuawuyts/choo#78]
For benchmarking and production uses, we should probably be recommending compiling template tags beforehand so that hyperx doesn't have to do it at runtime.

Here's an official transform by the author: https://www.npmjs.com/package/hyperxify
I still haven't found anything for webpack/rollup, but I'm still looking.

**Comment by toddself** [comment]
Yo-yoify also works well with choo!

**Comment by timwis** [comment]
Yep - see #3

**Comment by yoshuawuyts** [comment]
There's a section on optimizing choo here - https://github.com/yoshuawuyts/choo#how-can-i-optimize-choo; once v3 settles in we'll add the `yo-yoify` compilation step in there for sure. Like Tim said, #3 is the issue for that.

I hope this answers your question; if you're doing benchmarks I think I speak for everyone we'd be heaps interested in hearing the results! :sparkles: I'm closing this issue for now, though if you feel we've missed anything I'd be happy to reopen. Cheers!
