### ISSUE TITLE
Rename "app" model namespace?

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/choo#82]
Per convo in IRC, the [`app` model](https://github.com/yoshuawuyts/choo/blob/master/index.js#L202-L230) really only deals with `location` (the route), potentially the [`params`](https://github.com/yoshuawuyts/choo/issues/35), and subscriptions to hash, history, anchor links - all to do with navigating. @yoshuawuyts and I were discussing the idea of renaming the namespace to something like `location`, `navigator`, or `url`. Yosh pointed out `location` has a parallel to `window.location` so may be the best choice.

Thoughts?

**Comment by yoshuawuyts** [comment]
Yup, I like this. I'd keep `state.params` as separate though, as it bears similarities to `react-router` (`this.props.params`) and is easier to access which makes for better UX

**Comment by yoshuawuyts** [comment]
Closing as 3.0 is imminent; wanna make sure all issues are taken care of. Releasing soooon™ :sparkles:
