### ISSUE TITLE
docs - mention default container

### ISSUE THREAD

**Issue by kumavis** [yoshuawuyts/choo#84]
in general the `app.start()` API is not clearly documented. I start the app and the first thing I get is 
```
Could not find DOM node '#choo-root' to update
```

**Comment by yoshuawuyts** [comment]
Oh interesting - so I take it you didn't append to the DOM right? In the docs under `API` for `app.start()` it says:
> Start the application. Returns a tree of DOM nodes that can be mounted using document.body.appendChild().

Perhaps we should mention it _should_ be mounted; does that make sense? Perhaps expand the error message further to mention you might've forgotten to append it to the DOM?

**Comment by kumavis** [comment]
ah yes that must have been the problem

**Comment by kumavis** [comment]
my random walk / brute force approach to coding got me this 'solution':
```js
var container = document.createElement('div')
document.body.appendChild(container)
container.id = 'app-container'
app.start('#app-container')


function view (params, state, send) {
  return createElement(

    h('#app-container', [
      renderRoot(state.viz, send)
    ])

  )
} 
```
your version is much better

**Comment by kumavis** [comment]
nice
``js
var tree = app.start()
document.body.appendChild(tree)


function view (params, state, send) {
  return createElement(

    renderRoot(state.viz, send)

  )
}
```

**Comment by yoshuawuyts** [comment]
@kumavis should we do anything doc-wise or you reckon it's good?

**Comment by yoshuawuyts** [comment]
I hope this was resolved - closing for now; if this is still an issue happy to reopen! :sparkles:
