### ISSUE TITLE
Fetching data for a view

### ISSUE THREAD

**Issue by callum** [yoshuawuyts/choo#88]
I have some views that depend on data from a remote source, but I can't figure out where the request(s) should happen. I'm trying to keep the HTTP code separate from my views so that requests aren't made every time the app renders. Any advice here?

**Comment by toddself** [comment]
Are the data coming in based on a user action or does it arrive by default when the page loads?

If its on a user action you could call a method from an effect and when it finishes call send in the callback (effects are async).

If not you could use some sort of events (an emitter, a pull stream, etc) to trigger in a subscription (like the SSE example). 

Does that make sense?

**Comment by callum** [comment]
Hi @toddself - it arrives by default when the page loads. What makes this slightly more tricky is that it requires the params and state of the current view/route to be able to request the correct data.

**Comment by toddself** [comment]
Can you attach a listener to DOM content loaded which requests the content and then have that fire a subscription when it arrives?

**Comment by timwis** [comment]
@callum one approach is to store whether or not the data has been fetched in the state, and fetch it in the view if `isFetched = false` ([demo](http://requirebin.com/?gist=348011cc3cf126265fd680e04658da93)). An alternative is to use [on-load](https://github.com/shama/on-load) to detect when the view is mounted to the dom. This is being [incorporated into choo v3](https://github.com/yoshuawuyts/choo/issues/42) though there's still an [outstanding issue](https://github.com/shama/on-load/issues/5) with it.

**Comment by callum** [comment]
Solved using a global cache of fetched URLs:

```js
const cache = require('./cache')

// model
const uri = 'http://localhost:8080/albums'
if (cache.has(uri)) return
const opts = {
  headers: { authorization: window.localStorage.token },
  json: true
}
http.get(uri, opts, (err, res, body) => {
  if (err || res.statusCode >= 400) {
    return send('app:error', { error: 'Something went wrong' })
  }
  cache.add(uri)
  send('albums:gotAll', { albums: body.data })
})
```
