### ISSUE TITLE
Connecting keyboard events and page transitions

### ISSUE THREAD

**Issue by josephg** [yoshuawuyts/choo#89]
I have a problem I'm trying to solve and I'm not sure the best way to solve it.

I have three pages `/details/alice`, `/details/bill` and `/details/charlie`, rendered from a `/details/:name` route. Each page has left and right arrows to flip between pages (alice -> bill -> charlie -> alice). My problem is that I also want the left and right arrow keys on the keyboard to make those transitions.

I'm trying to figure out the best way to do it with choo. All the solutions I can think of are a bit gross.

1. I can subscribe to `window.onkeydown` in a subscription. That would fire a `next` event, in which I could look up the current page, figure out the next page and transition there. Unfortunately:
  - The router's `props` aren't exposed in the app's state object. So to do it I'd need to parse out the props from `app:location` or something.
  - The view is already figuring out the URL to transition to in its next / previous links. It feels a bit off to share that logic between model code and view code.
2. Same as above, but I can look for the links in the page from the handler, and call `.click()` on them. This is what I've settled on, but its a bit weird and unwieldy. I also want to add more handlers, and needing to hook them up from two different places seems strange

Discarded options:

1. The view can attach global `window.next()` and `window.prev()` functions, which is super gross.
2. The view can attach global `window.onkeydown` event handlers. (In a sense which pages are next and previous are a property of the current view). The bad thing with this is that I would then want to remove those handlers when I transition to any other route, but without a way to have routing middleware this is difficult.

I feel like I want my route to expose a set of keyboard event handlers (this is a little game, so thats not crazy). But ... I need a way to reset them on route transition. And I'm not sure if they should live in the state object, which feels like it should be `JSON.stringify()`-able.

I'd love to hear some thoughts on the best way to do this sort of thing. (Sorry for abusing the issue tracker - let me know if there's a better place for questions like this.)

**Comment by yoshuawuyts** [comment]
> Sorry for abusing the issue tracker - let me know if there's a better place for questions like this

No need to apologize; questions and feedback is more than welcome! - If anything it shows us where people are strugging and where in the docs and API we should improve. So thank _you_ :sparkles:

---

> I can subscribe to window.onkeydown in a subscription. That would fire a next event, in which I could look up the current page, figure out the next page and transition there

I think the first option you laid out would make the most sense from a UX point of view. A keyboard event is called, you extract the current `param` from the `state` and then you cycle to the next route accordingly. This should be possible in the next release with the new `view` API (https://github.com/yoshuawuyts/choo/issues/35#issuecomment-228498988).

Regarding setting listeners on elements / views - when https://github.com/shama/bel/pull/32 lands and we update dependencies we should be getting it for free, effectively closing #1. That should fix your issue right?

I hope this answers your questions. We should definitely be updating the docs when this lands. Cheers!

**Comment by josephg** [comment]
Yep those changes would do the trick nicely! Looking forward to them landing. Thanks!
