### ISSUE TITLE
Multi-pages with layout?

### ISSUE THREAD

**Issue by crapthings** [yoshuawuyts/choo#92]
how to replace main content while navigate through router

**Comment by yoshuawuyts** [comment]
You can nest functions like this:
```js
const app = choo()

app.router((route) => [
  route('/foo', common(fooView)),
  route('/bar', common(barView))
])

function common (mainView) {
  return function (params, state, send) {
    return html`
      <aside>sidebar content</aside>
      <main>${mainView(params, state, send)}</main>
    `
  }
}

function fooView (params, state, send) {
  return html`<div>foo</div>`
}

function barView (params, state, send) {
  return html`<div>bar</div>`
}
```
The `morphdom` algorithm should do the work to ensure these transitions happen as smooth as possible. Does this answer your question?

**Comment by hew** [comment]
@yoshuawuyts I think that should be `` view` `` instead of `` html` ``.

**Comment by yoshuawuyts** [comment]
@hew oh, I nowadays usually do `const html = choo.view` to have parity with `const css = require('sheetify')` from [sheetify](https://github.com/stackcss/sheetify)

Using `css` and `html` as var names makes stuff pretty straight forward I've found :sparkles:

**Comment by hew** [comment]
@yoshuawuyts That makes sense. 👍🏽

**Comment by yoshuawuyts** [comment]
I'm going to assume this solves your issue. Thanks for opening! :sparkles:
