### ISSUE TITLE
Mailbox example is unable to be run in current state

### ISSUE THREAD

**Issue by toddself** [yoshuawuyts/choo#96]
Missing a requirement on tachyons and pathname-split, but even if those two are added, errorify spits out an error with Tachyons not being where it expects it to be.

This is an issue in verifying the changes in #95 for this example

**Comment by toddself** [comment]
Seems like #73 resolves some other issues.

**Comment by yoshuawuyts** [comment]
Just merged #73; going to have to dig into what's going wrong here

**Comment by yoshuawuyts** [comment]
This is the weirdest bug - running into this too rn... what the hell :/

**Comment by yoshuawuyts** [comment]
doesn't seem to happen when `browserify` is run without `bankai` - fuck it; omitting `tachyons` for now then
