### ISSUE TITLE
Breakout examples in to separate repo? (or repos)

### ISSUE THREAD

**Issue by toddself** [yoshuawuyts/choo#97]
Might be worth while to break out examples into separate repos and add tests for them so that people might get a better holistic view of a choo app?

**Comment by guido4000** [comment]
Yes, and adding an explanation on how to run them (e.g. with budo) would be helpful, too.

**Comment by toddself** [comment]
@guido4000 you should be able to `npm install && npm start` in most of the examples and run them.  The mail one needs some more love though :)

**Comment by guido4000** [comment]
In the title example I can only see one js file.
https://github.com/yoshuawuyts/choo/tree/master/examples/title

**Comment by toddself** [comment]
@guido4000 the title example is the one linked to from the [README](https://github.com/yoshuawuyts/choo#demos)
[input example](http://requirebin.com/?gist=e589473373b3100a6ace29f7bbee3186)

There is no server for it because it saves nothing. Just a demo of the flow of data.

**Comment by guido4000** [comment]
Yes, I just came across the examples folder and tried to run it locally. So some hint on how to run it would have been helpful.

**Comment by yoshuawuyts** [comment]
@toddself maybe? I agree they could be better documented and tests would be useful but.... right now they're a great way of debugging existing builds of `choo`; and having them live inside this repo is great for that. If learning is the objective, perhaps https://github.com/yoshuawuyts/workshop-choo is the way to go?

If people then want to run examples, there we could be better on linking cool examples from the README. Does this sound reasonable?

**Comment by toddself** [comment]
@yoshuawuyts yeah I realized that after I did the HTML split thing that they're SUPER helpful for realizing what I've messed up :laughing:
