### ISSUE TITLE
Rendering a separate component at a later stage

### ISSUE THREAD

**Issue by chrisbuttery** [yoshuawuyts/choo#98]
I'm having an issue rendering a separate component (with it's own state) at a later time.

In this example, `app2` is something I'd like to render at a later stage. Perhaps a user clicked a button and this component would populate a modal window.
To make things as simple as possible, this example attempts to load `app2` after 3 seconds via `setTimeout()`.

![no-worky](https://cloud.githubusercontent.com/assets/121675/16472518/fbb9b3be-3ea7-11e6-9c34-7397bd319ce6.gif)

```js
const choo = require('choo')

// app 1
const app1 = choo()

app1.model({
  state: {
    data: 'app1',
  },
  reducers: {
    update: (action, state) => ({data: action.value})
  }
})

function app1main (params, state, send) {
  return choo.view`<button onclick=${(evt) => send('update', {value: 'app2main'})}>${state.data}</button>`
}

app1.router((route) => [
  route('/', app1main)
])

const tree1 = app1.start({name: 'app1'})
document.body.appendChild(tree1)


// app 2
// subcribes to 'init' to trigger the start of a countdown
const app2 = choo()

function init (send) {
  send('start', { payload: send })
}

app2.model({
  state: {
    data: 'app2',
    count: 5,
    timer: null
  },
  reducers: {
    update: (action, state) => ({data: action.value}),
    start: (action, state)=> {{
      timer: setInterval(() => { action.payload('tick')}, 1000)
    }},
    tick: (action, state) => ({
      count: state.count - 1
    })
  },
  subscriptions: [init]
})

function app2main (params, state, send) {
  return choo.view`<button onclick=${(evt) => send('update', {value: 'app1main'})}>${state.data} ${state.count}</button>`
}

app2.router((route) => [
  route('/', app2main)
])

setTimeout(function() {
  const tree2 = app2.start({name: 'app2'})
  document.body.appendChild(tree2)
}, 3000)
```

You'd notice that the 2 apps render, but nothing is really happening.
Removing the `setTimeout` from the rendering of `app2` so they render at the same time, you'll notice `app2` will start decrementing.

![worky](https://cloud.githubusercontent.com/assets/121675/16472526/0471d1f8-3ea8-11e6-9295-e7971a3fef2f.gif)

Is there a way around this ?

**Comment by toddself** [comment]
This is an issue with how you're using the reducers:

```js
start: (action, state)=> {{
      timer: setInterval(() => { action.payload('tick')}, 1000)
    }}
```
Reducers are synchronous -- in order to update state they must return a value -- this returns `undefined`.  This should probably be moved into an effect as effects also have access to `send` in their scope.  (You've also got some superfluous `{}` on that function).  By calling another reducer from inside of a reducer you're causing some odd re-rendering of the DOM to happen since calling an action triggers a run of the DOM updater.

If you move this to an effect, this works as expected in this example:
[requirebin](http://requirebin.com/?gist=4ab2e68102ee27492761c3e5a461e254)

```js
app2.model({
  state: {
    data: 'app2',
    count: 5,
    timer: null
  },
  effects: {
    start: (action, state, send) => setInterval(() => send('tick'), 1000)
  },
  reducers: {
    update: (action, state) => ({data: action.value}),
    tick: (action, state) => ({
      count: state.count - 1
    })
  },
  subscriptions: [init]
})
```

**Comment by chrisbuttery** [comment]
@toddself Thanks so much, that makes total sense.
This works as expected in requirebin, however it doesn't seem to be decrementing in a local build. Weird.

**Comment by chrisbuttery** [comment]
@toddself Scrap that - it is. I'll shut up. Thank you.

**Comment by chrisbuttery** [comment]
@toddself Actually I don't think it is (with the setTimeout()) but I'll investigate further.

**Comment by toddself** [comment]
This works for me locally using [budo](https://github.com/mattdesl/budo)

`budo test.js --open`
![image](https://cloud.githubusercontent.com/assets/193412/16473880/80b2ff26-3e26-11e6-8a49-fd1d00a21c41.png)

**Comment by chrisbuttery** [comment]
@toddself 
Yeah works for me now. Something weird was happening and it wasn't decrementing in chrome or FF.
I'm just glad it made me look like such a newb.
Thanks again

**Comment by toddself** [comment]
There is no newb here :smile:! I get stuck on the smallest things sometimes for hours.

Good luck! Hope you enjoy conducting the train!

**Comment by chrisbuttery** [comment]
`toot toot!`
